### ISSUE TITLE
Could not connect PeerConnection after timeout

### ISSUE THREAD

**Issue by burzomir** [livekit/livekit#1299]
**Describe the bug**
LiveKit's built in TURN doesn't work for some users. Using other TURN servers works. All major browsers are affected. 

**Server**
- Version: [1.3.3]
- Environment: [Docker]

**Client**
- SDK: [js]
- Version: [1.5.0]

**Additional context**

```
port: 7880
rtc:
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 60000
    use_external_ip: true
    turn_servers:
        - host: turn.mycompany.com
          port: 3478
          protocol: udp

        - host: turn.mycompany.com
          port: 443
          protocol: tcp

        - host: turn.mycompany.com
          port: 80
          protocol: tcp

...

# turn:
#     enabled: true
#     domain: mycompany.com
#     cert_file: ""
#     key_file: ""
#     tls_port: 5349
#     udp_port: 443
#     external_tls: true

```

[webrtc_internals_dump.txt](https://github.com/livekit/livekit/files/10390450/webrtc_internals_dump.txt)

**Comment by cnderrauber** [comment]
Can you post your server and network config? If all major browsers are affected, it would relate to specific networks

**Comment by burzomir** [comment]
@cnderrauber  What info do you need exactly?

**Comment by TheOptimisticFactory** [comment]
We are also experiencing the same issue using `livekit-server v1.3.3`

Using `v13.3` 
- On chromium, it yields ``




<details>
  <summary>Here is the config used in our case (click to expand)</summary>
  
  ```yaml
# ===================== PORTS ===================== #

port: 7880

rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: true

# ===================== SECURITY ===================== #

keys:
  <REDACTED>

webhook:
  <REDACTED>
  urls: 
    - <REDACTED>

# ===================== LOGS ===================== #

logging:
  json: false
  level: debug
  pion_level: debug

# ===================== REDIS ===================== #

redis:
  address: <REDACTED>
  db: 1
  password: <REDACTED>
  username: <REDACTED>

# ===================== TURN ===================== #

turn:
  enabled: true
  udp_port: 3478
  domain: <REDACTED>
```
</details>

**Comment by davidzhao** [comment]
can you post the IP addresses that are assigned to the server?

**Comment by cnderrauber** [comment]
@burzomir Can you post your server's ifconfig output and livekitserver's starting log, also, the port you are opened to the public address

**Comment by cnderrauber** [comment]
@TheOptimisticFactory Can you post your server config too? you can use a fake ip instead of your real ip address (1:1 mapping), the v1.3.3 has ignored the private ip candidate for firefox, but your public address might can't be access by the client

**Comment by TheOptimisticFactory** [comment]
> @TheOptimisticFactory Can you post your server config too? you can use a fake ip instead of your real ip address (1:1 mapping), the v1.3.3 has ignored the private ip candidate for firefox, but your public address might can't be access by the client

<details>
  <summary>Here is the compose file for livekit-server (click to expand)</summary>
  
  ```yaml
  version: '3.8'

  x-DEPLOY_CONSTRAINTS_LIVEKIT_SERVER: &DEPLOY_CONSTRAINTS_LIVEKIT_SERVER
    placement:
      constraints:
        - node.labels.type == webrtc-livekit
    replicas: 1
    restart_policy:
      condition: on-failure

  services:

    #===============================================================================================#
    #                                            LIVEKIT                                            #
    #===============================================================================================#

    livekit:
      image: "{{ DOCKER_IMAGES.LIVEKIT }}"
      deploy: *DEPLOY_CONSTRAINTS_LIVEKIT_SERVER
      environment:
        LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
        LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
        LIVEKIT_DOMAIN_NAME: ${LIVEKIT_DOMAIN_NAME}
        LIVEKIT_LOG_LEVEL: "debug"
        LIVEKIT_PORT: ${LIVEKIT_PORT}
        LIVEKIT_WEBHOOK_URL: ${LIVEKIT_WEBHOOK_URL}
        REDIS_URL: "${REDIS_URL}"
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        RUNTIME_OPTIONS: ${LIVEKIT_RUNTIME_OPTIONS}
      networks:
        - proxy
      ports:
        - "80"              # for TLS issuance
        - "443"             # for primary HTTPS and TURN/TLS
        - "3478:3478"       # Custom port for TURN over UDP
        - "3478:3478/udp"   # Custom port for TURN over UDP
        - "7880:7880"       # main TCP port for RoomService and RTC endpoint
        - "7881:7881"       # for WebRTC over TCP
        - "7882:7882"       # for WebRTC over UDP
        - "7882:7882/udp"   # for WebRTC over UDP

  networks:
    proxy:
      # NOTE: This is just a regular docker swarm network (using the default "overlay" driver)
      external: true
```
</details>

<details>
  <summary>Along with its associated .env file (click to expand)</summary>
  
  ```yaml
  # ========================================= #
  #                  LIVEKIT                  #
  # ========================================= #

  LIVEKIT_API_KEY=<REDACTED>
  LIVEKIT_API_SECRET=<REDACTED>
  LIVEKIT_DOMAIN_NAME=<REDACTED>
  LIVEKIT_PORT=7880
  # NOTE: The public IP of the swarm servers is provided in the following runtime option
  LIVEKIT_RUNTIME_OPTIONS="--node-ip <REDACTED_IP>"
  LIVEKIT_WEBSOCKET_URL=ws://livekit:7880
  LIVEKIT_WEBHOOK_URL=<REDACTED>

  # ======================================= #
  #                  REDIS                  #
  # ======================================= #

  REDIS_HOST=redis
  REDIS_PASSWORD=<REDACTED>
  REDIS_PORT=6379
  REDIS_URL=redis:6379
  REDIS_USER=<REDACTED>
```
</details>

-- 

Note: We are using custom docker images of livekit-server to support changing the config file using env variables. It has 0 functional differences otherwise. 

<details>
  <summary>For reference, this is the dockerfile</summary>
  
  ```yaml
  # - Docker image: https://hub.docker.com/r/livekit/livekit-server
  # - Releases: https://github.com/livekit/livekit/releases
  FROM livekit/livekit-server:v1.3.3

  # ============================== #
  # 01. Copy templated config file #
  # ============================== #

  COPY config.livekit.baseline.yaml /etc/config.livekit.baseline.yaml

  # ================= #
  # 02. Runtime start #
  # ================= #

  COPY entrypoint.sh /entrypoint.sh
  RUN chmod +x /entrypoint.sh
  ENTRYPOINT [ "/entrypoint.sh" ]
```
</details>

<details>
  <summary>For reference, this is the templated config file used in the dockerfile (click to expand)</summary>
  
  ```yaml
  # ===================== PORTS ===================== #

  port: ${LIVEKIT_PORT}

  rtc:
    tcp_port: 7881
    udp_port: 7882
    use_external_ip: true
    use_ice_lite: false

  # ===================== SECURITY ===================== #

  keys:
    ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}

  webhook:
    api_key: ${LIVEKIT_API_KEY}
    urls: ${LIVEKIT_WEBHOOK_URL}

  # ===================== LOGS ===================== #

  logging:
    json: false
    level: ${LIVEKIT_LOG_LEVEL}
    pion_level: ${LIVEKIT_LOG_LEVEL}

  # ===================== REDIS ===================== #

  redis:
    address: ${REDIS_URL}
    db: 1
    password: ${REDIS_PASSWORD}
    username: ${REDIS_USERNAME}

  # ===================== TURN ===================== #

  turn:
    enabled: true
    udp_port: 3478
    domain: ${LIVEKIT_DOMAIN_NAME}
    cert_file: ${LIVEKIT_TLS_CERTIFICATE_PATH}
    key_file: ${LIVEKIT_TLS_KEY_PATH}
```
</details>

<details>
  <summary>For reference, this is an extract of the script entrypoint.sh used in the dockerfile</summary>
  
  ```bash
#!/bin/sh
set -e

FINAL_CONFIG="/etc/livekit.yaml"

# 01 > duplicate runtime config file from template
cp /etc/config.livekit.baseline.yaml ${FINAL_CONFIG}

# 02 > replace template values with the actual environment values
sed -i "s/\${LIVEKIT_API_KEY}/${LIVEKIT_API_KEY}/" "${FINAL_CONFIG}"
sed -i "s/\${LIVEKIT_API_SECRET}/${LIVEKIT_API_SECRET}/" "${FINAL_CONFIG}"
# ...

# 03 > Start the livekit server
/livekit-server --config ${FINAL_CONFIG}  ${RUNTIME_OPTIONS}

```
</details>

**Comment by burzomir** [comment]
@cnderrauber 

<details>
<summary>ifconfig</summary>
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:b3:09:ad:55  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

 

enp0s16: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 91.250.106.15  netmask 255.255.255.224  broadcast 91.250.106.31
        inet6 2a02:cbf3:22e:1:2037:aff:fede:e901  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::2037:aff:fede:e901  prefixlen 64  scopeid 0x20<link>
        inet6 2a02:cbf3:22e:1:ffff::16  prefixlen 128  scopeid 0x0<global>
        ether 22:37:0a:de:e9:01  txqueuelen 1000  (Ethernet)
        RX packets 20985889  bytes 13400361574 (13.4 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14133207  bytes 9347743570 (9.3 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

 

enp0s17: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.97.11  netmask 255.255.255.0  broadcast 10.0.97.255
        inet6 fe80::2037:aff:fede:e902  prefixlen 64  scopeid 0x20<link>
        ether 22:37:0a:de:e9:02  txqueuelen 1000  (Ethernet)
        RX packets 6972  bytes 721931 (721.9 KB)
        RX errors 0  dropped 5  overruns 0  frame 0
        TX packets 1498  bytes 316025 (316.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

 

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 3884680  bytes 505984979 (505.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3884680  bytes 505984979 (505.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
</details>
port: no firewall
<details>
<summary>routing</summary>
default via 91.250.106.1 dev enp0s16 proto dhcp src 91.250.106.15 metric 100
8.8.4.4 via 91.250.106.1 dev enp0s16 proto dhcp src 91.250.106.15 metric 100
8.8.8.8 via 91.250.106.1 dev enp0s16 proto dhcp src 91.250.106.15 metric 100
10.0.66.0/24 via 10.0.97.1 dev enp0s17 proto static metric 100 onlink
10.0.96.0/24 via 10.0.97.1 dev enp0s17 proto static metric 100 onlink
10.0.97.0/24 via 10.0.97.1 dev enp0s17 proto static metric 100 onlink
10.0.97.0/24 dev enp0s17 proto kernel scope link src 10.0.97.11 metric 100
91.250.106.0/27 dev enp0s16 proto kernel scope link src 91.250.106.15 metric 100
91.250.106.1 dev enp0s16 proto dhcp scope link src 91.250.106.15 metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
216.239.35.0 via 91.250.106.1 dev enp0s16 proto dhcp src 91.250.106.15 metric 100
216.239.35.8 via 91.250.106.1 dev enp0s16 proto dhcp src 91.250.106.15 metric 100
</details>
<details>
<summary>beginning of live kit-server's logs</summary>
2023-01-10T11:49:15.072Z	INFO	livekit	redis/redis.go:82	connecting to redis	{"simple": true, "addr": "localhost:6379"}
2023-01-10T11:49:15.315Z	INFO	livekit	redis/redis.go:82	connecting to redis	{"simple": true, "addr": "localhost:6379"}
2023-01-10T11:49:16.388Z	INFO	livekit	rtc/config.go:321	failed to get external ip	{"local": "172.17.0.1", "err": "could not validate external IP"}
2023-01-10T11:49:16.391Z	INFO	livekit	rtc/config.go:321	failed to get external ip	{"local": "10.0.97.11", "err": "could not determine public IP"}
2023-01-10T11:49:16.391Z	INFO	livekit	rtc/config.go:105	using external IPs	{"ips": ["91.250.106.15/91.250.106.15", "10.0.97.11/10.0.97.11", "172.17.0.1/172.17.0.1"]}
2023-01-10T11:49:16.392Z	INFO	livekit	service/turn.go:127	Starting TURN server	{"turn.relay_range_start": 30000, "turn.relay_range_end": 40000, "turn.portTLS": 5349, "turn.externalTLS": true, "turn.portUDP": 443}
2023-01-10T11:49:16.394Z	INFO	livekit	service/server.go:212	starting LiveKit server	{"portHttp": 7880, "nodeID": "ND_MJd5gtdO", "nodeIP": "91.250.106.15", "version": "1.3.3", "rtc.portTCP": 7881, "rtc.portICERange": [50000, 60000]}
2023-01-10T11:58:34.816Z	INFO	livekit	service/roomallocator.go:111	selected node for room	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "selectedNodeID": "ND_MJd5gtdO"}
2023-01-10T11:58:34.819Z	INFO	livekit	rtc/room.go:308	new participant joined	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "pID": "PA_iA2TrfgAwKq4", "participant": "643", "protocol": 8, "options": {"AutoSubscribe":true}}
2023-01-10T11:58:34.820Z	INFO	livekit	service/rtcservice.go:266	new client WS connected	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "participant": "643", "pID": "PA_iA2TrfgAwKq4", "remote": false, "connID": "CO_nex8XMohRPAo"}
2023-01-10T11:58:34.820Z	INFO	livekit	rtc/room.go:257	participant state changed	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "state": "JOINED", "participant": "643", "pID": "PA_iA2TrfgAwKq4", "oldState": "JOINING"}
2023-01-10T11:58:35.539Z	INFO	livekit	rtc/transport.go:509	selected ICE candidate pair	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "participant": "643", "pID": "PA_iA2TrfgAwKq4", "remote": false, "transport": "SUBSCRIBER", "pair": "(local) udp4 host 91.250.106.15:59734 <-> (remote) udp4 srflx 37.140.39.213:50037 related 192.168.0.105:50037"}
2023-01-10T11:58:49.900Z	INFO	livekit	service/rtcservice.go:236	finishing WS connection	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "participant": "643", "pID": "PA_iA2TrfgAwKq4", "remote": false, "connID": "CO_nex8XMohRPAo"}
2023-01-10T11:59:05.539Z	INFO	livekit	rtc/transport.go:528	peer connection failed	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "participant": "643", "pID": "PA_iA2TrfgAwKq4", "remote": false, "transport": "SUBSCRIBER"}
2023-01-10T11:59:05.539Z	INFO	livekit	rtc/transport.go:492	short ICE connection	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "participant": "643", "pID": "PA_iA2TrfgAwKq4", "remote": false, "transport": "SUBSCRIBER", "pair": "(local) udp4 host 91.250.106.15:59734 <-> (remote) udp4 srflx 37.140.39.213:50037 related 192.168.0.105:50037", "duration": "30.000679398s"}
2023-01-10T11:59:05.539Z	INFO	livekit	rtc/transportmanager.go:554	prefer TCP transport on both peer connections	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "participant": "643", "pID": "PA_iA2TrfgAwKq4", "remote": false}
2023-01-10T11:59:05.540Z	INFO	livekit	rtc/transportmanager.go:470	setting ICE config	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "participant": "643", "pID": "PA_iA2TrfgAwKq4", "remote": false, "iceConfig": "preference_subscriber:ICT_TCP preference_publisher:ICT_TCP"}
2023-01-10T11:59:05.540Z	INFO	livekit	rtc/participant_signal.go:232	closing signal connection	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "participant": "643", "pID": "PA_iA2TrfgAwKq4", "remote": false}
2023-01-10T11:59:20.540Z	INFO	livekit	rtc/participant.go:1347	closing disconnected participant	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "participant": "643", "pID": "PA_iA2TrfgAwKq4", "remote": false}
2023-01-10T11:59:20.540Z	INFO	livekit	rtc/participant.go:614	participant closing	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "participant": "643", "pID": "PA_iA2TrfgAwKq4", "remote": false, "sendLeave": true, "reason": "PEER_CONNECTION_DISCONNECTED"}
2023-01-10T11:59:20.540Z	INFO	livekit	rtc/participant_signal.go:215	could not send message to participant	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "participant": "643", "pID": "PA_iA2TrfgAwKq4", "remote": false, "messageType": "*livekit.SignalResponse_Leave"}
2023-01-10T11:59:20.541Z	INFO	livekit	rtc/room.go:257	participant state changed	{"room": "501053874", "roomID": "RM_CtteWT22CHMk", "state": "DISCONNECTED", "participant": "643", "pID": "PA_iA2TrfgAwKq4", "oldState": "JOINED"}
2023-01-10T11:59:40.395Z	INFO	livekit	rtc/room.go:573	closing room	{"room": "501053874", "roomID": "RM_CtteWT22CHMk"}
2023-01-10T11:59:40.395Z	INFO	livekit	service/roommanager.go:110	deleting room state	{"room": "501053874"}
2023-01-10T11:59:40.395Z	INFO	livekit	service/roommanager.go:427	room closed	{"room": "501053874", "roomID": "RM_CtteWT22CHMk"}
2023-01-10T12:00:06.245Z	INFO	livekit	service/roomallocator.go:111	selected node for room	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "selectedNodeID": "ND_MJd5gtdO"}
2023-01-10T12:00:06.247Z	INFO	livekit	rtc/room.go:308	new participant joined	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "pID": "PA_2rQkw4dsSEQk", "participant": "644", "protocol": 8, "options": {"AutoSubscribe":true}}
2023-01-10T12:00:06.248Z	INFO	livekit	service/rtcservice.go:266	new client WS connected	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "participant": "644", "pID": "PA_2rQkw4dsSEQk", "remote": false, "connID": "CO_d5xZS4ve2k9u"}
2023-01-10T12:00:06.248Z	INFO	livekit	rtc/room.go:257	participant state changed	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "state": "JOINED", "participant": "644", "pID": "PA_2rQkw4dsSEQk", "oldState": "JOINING"}
2023-01-10T12:00:06.963Z	INFO	livekit	rtc/transport.go:509	selected ICE candidate pair	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "participant": "644", "pID": "PA_2rQkw4dsSEQk", "remote": false, "transport": "SUBSCRIBER", "pair": "(local) udp4 host 91.250.106.15:52876 <-> (remote) udp4 srflx 37.140.39.213:59230 related 192.168.0.105:59230"}
2023-01-10T12:00:21.324Z	INFO	livekit	service/rtcservice.go:236	finishing WS connection	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "participant": "644", "pID": "PA_2rQkw4dsSEQk", "remote": false, "connID": "CO_d5xZS4ve2k9u"}
2023-01-10T12:00:36.963Z	INFO	livekit	rtc/transport.go:528	peer connection failed	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "participant": "644", "pID": "PA_2rQkw4dsSEQk", "remote": false, "transport": "SUBSCRIBER"}
2023-01-10T12:00:36.964Z	INFO	livekit	rtc/transport.go:492	short ICE connection	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "participant": "644", "pID": "PA_2rQkw4dsSEQk", "remote": false, "transport": "SUBSCRIBER", "pair": "(local) udp4 host 91.250.106.15:52876 <-> (remote) udp4 srflx 37.140.39.213:59230 related 192.168.0.105:59230", "duration": "30.000461071s"}
2023-01-10T12:00:36.964Z	INFO	livekit	rtc/transportmanager.go:554	prefer TCP transport on both peer connections	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "participant": "644", "pID": "PA_2rQkw4dsSEQk", "remote": false}
2023-01-10T12:00:36.964Z	INFO	livekit	rtc/transportmanager.go:470	setting ICE config	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "participant": "644", "pID": "PA_2rQkw4dsSEQk", "remote": false, "iceConfig": "preference_subscriber:ICT_TCP preference_publisher:ICT_TCP"}
2023-01-10T12:00:36.964Z	INFO	livekit	rtc/participant_signal.go:232	closing signal connection	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "participant": "644", "pID": "PA_2rQkw4dsSEQk", "remote": false}
2023-01-10T12:00:51.965Z	INFO	livekit	rtc/participant.go:1347	closing disconnected participant	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "participant": "644", "pID": "PA_2rQkw4dsSEQk", "remote": false}
2023-01-10T12:00:51.965Z	INFO	livekit	rtc/participant.go:614	participant closing	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "participant": "644", "pID": "PA_2rQkw4dsSEQk", "remote": false, "sendLeave": true, "reason": "PEER_CONNECTION_DISCONNECTED"}
2023-01-10T12:00:51.965Z	INFO	livekit	rtc/participant_signal.go:215	could not send message to participant	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "participant": "644", "pID": "PA_2rQkw4dsSEQk", "remote": false, "messageType": "*livekit.SignalResponse_Leave"}
2023-01-10T12:00:51.966Z	INFO	livekit	rtc/room.go:257	participant state changed	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA", "state": "DISCONNECTED", "participant": "644", "pID": "PA_2rQkw4dsSEQk", "oldState": "JOINED"}
2023-01-10T12:00:59.043Z	INFO	livekit	service/roomallocator.go:111	selected node for room	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "selectedNodeID": "ND_MJd5gtdO"}
2023-01-10T12:00:59.045Z	INFO	livekit	rtc/room.go:308	new participant joined	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "pID": "PA_2JXtd6sHJ2Ee", "participant": "645", "protocol": 8, "options": {"AutoSubscribe":true}}
2023-01-10T12:00:59.046Z	INFO	livekit	rtc/room.go:257	participant state changed	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "state": "JOINED", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "oldState": "JOINING"}
2023-01-10T12:00:59.046Z	INFO	livekit	service/rtcservice.go:266	new client WS connected	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "connID": "CO_YWUWDDGE4WRX"}
2023-01-10T12:01:00.130Z	INFO	livekit	rtc/transport.go:509	selected ICE candidate pair	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "transport": "SUBSCRIBER", "pair": "(local) udp4 host 91.250.106.15:51124 <-> (remote) udp4 prflx 91.90.163.34:56591 related :0"}
2023-01-10T12:01:00.313Z	INFO	livekit	rtc/room.go:257	participant state changed	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "state": "ACTIVE", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "oldState": "JOINED"}
2023-01-10T12:01:02.503Z	INFO	livekit	rtc/participant.go:1567	pending track added	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "track": "sid:\"TR_VCZKPGjdszgY55\" type:VIDEO width:1280 height:720 source:CAMERA layers:{width:320 height:180 bitrate:120000} layers:{quality:MEDIUM width:640 height:360 bitrate:300000} layers:{quality:HIGH width:1280 height:720 bitrate:1700000}", "request": "cid:\"cb4d6a95-e607-460b-a07c-0235c8512978\" type:VIDEO width:1280 height:720 source:CAMERA layers:{width:320 height:180 bitrate:120000} layers:{quality:MEDIUM width:640 height:360 bitrate:300000} layers:{quality:HIGH width:1280 height:720 bitrate:1700000}"}
2023-01-10T12:01:02.723Z	INFO	livekit	rtc/transport.go:509	selected ICE candidate pair	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "transport": "PUBLISHER", "pair": "(local) udp4 host 91.250.106.15:52689 <-> (remote) udp4 srflx 91.90.163.34:54022 related 192.168.50.44:54022"}
2023-01-10T12:01:02.820Z	INFO	livekit	sfu/streamtrackermanager.go:405	available layers changed - layer seen	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "relayed": false, "mime": "video/vp8", "added": 0, "availableLayers": [0], "exemptedLayers": []}
2023-01-10T12:01:02.820Z	INFO	livekit	rtc/participant.go:1239	mediaTrack published	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "kind": "video", "trackID": "TR_VCZKPGjdszgY55", "rid": "q", "SSRC": 2017524785, "mime": "video/VP8"}
2023-01-10T12:01:02.830Z	INFO	livekit	rtc/participant.go:1239	mediaTrack published	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "kind": "video", "trackID": "TR_VCZKPGjdszgY55", "rid": "h", "SSRC": 1834403804, "mime": "video/VP8"}
2023-01-10T12:01:02.830Z	INFO	livekit	sfu/streamtrackermanager.go:405	available layers changed - layer seen	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "relayed": false, "mime": "video/vp8", "added": 1, "availableLayers": [0, 1], "exemptedLayers": []}
2023-01-10T12:01:03.092Z	INFO	livekit	rtc/participant.go:1239	mediaTrack published	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "kind": "video", "trackID": "TR_VCZKPGjdszgY55", "rid": "f", "SSRC": 2737634024, "mime": "video/VP8"}
2023-01-10T12:01:03.093Z	INFO	livekit	sfu/streamtrackermanager.go:405	available layers changed - layer seen	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "relayed": false, "mime": "video/vp8", "added": 2, "availableLayers": [0, 1, 2], "exemptedLayers": []}
2023-01-10T12:01:11.394Z	INFO	livekit	rtc/room.go:573	closing room	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA"}
2023-01-10T12:01:11.395Z	INFO	livekit	service/roommanager.go:110	deleting room state	{"room": "501053874"}
2023-01-10T12:01:11.395Z	INFO	livekit	service/roommanager.go:427	room closed	{"room": "501053874", "roomID": "RM_LsgyHsXnzbyA"}
2023-01-10T12:01:12.821Z	INFO	livekit	rtc/dynacastmanager.go:228	committing quality change	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "relayed": false, "force": false, "committedMaxSubscribedQuality": {}, "maxSubscribedQuality": {"video/VP8":3}}
2023-01-10T12:01:12.821Z	INFO	livekit	rtc/participant.go:1494	sending max subscribed quality	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "qualities": [{"codec":"vp8","qualities":[{},{"quality":1},{"quality":2}]}], "max": [{"CodecMime":"video/VP8","Quality":3}]}
2023-01-10T12:01:13.330Z	INFO	livekit	sfu/streamtrackermanager.go:482	available layers changed - layer gone	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "relayed": false, "mime": "video/vp8", "removed": 1, "availableLayers": [0, 2], "exeptedLayers": []}
2023-01-10T12:01:13.594Z	INFO	livekit	sfu/streamtrackermanager.go:482	available layers changed - layer gone	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "relayed": false, "mime": "video/vp8", "removed": 2, "availableLayers": [0], "exeptedLayers": []}
2023-01-10T12:01:13.821Z	INFO	livekit	sfu/streamtrackermanager.go:482	available layers changed - layer gone	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "relayed": false, "mime": "video/vp8", "removed": 0, "availableLayers": [], "exeptedLayers": []}
2023-01-10T12:02:18.116Z	INFO	livekit	rtc/signalhandler.go:62	client leaving room	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false}
2023-01-10T12:02:18.116Z	INFO	livekit	rtc/participant.go:614	participant closing	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "sendLeave": true, "reason": "CLIENT_REQUEST_LEAVE"}
2023-01-10T12:02:18.116Z	INFO	livekit	rtc/mediatrackreceiver.go:526	removing all subscribers for mime	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "relayed": false, "mime": "video/VP8"}
2023-01-10T12:02:18.116Z	INFO	livekit	rtc/participant_signal.go:232	closing signal connection	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false}
2023-01-10T12:02:18.117Z	INFO	livekit	service/rtcservice.go:236	finishing WS connection	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "connID": "CO_YWUWDDGE4WRX"}
2023-01-10T12:02:18.118Z	INFO	livekit	buffer/buffer.go:317	rtp stats	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "relayed": false, "mime": "video/vp8", "layer": 2, "direction": "upstream", "stats": "t: Tue Jan 10 12:01:03 UTC 2023|Tue Jan 10 12:02:18 UTC 2023|75.03s sn: 26788|28707, ep: 1920|25.59/s, p: 1806|24.07/s, l: 0|0.0/s|0.00%, b: 1996610|212900.3bps|36528, f: 293|3.9/s / 1|Tue Jan 10 12:01:03 UTC 2023, d: 0|0.00/s, bd: 0|0.0bps|0, pp: 114|1.52/s, bp: 27816|2966.0bps|2280, o: 1, c: 90000, j: 31(347.6us)|31(347.6us), gh:[1:1], n:0|0|0|0, pli:0|Mon Jan  1 00:00:00 UTC 0001 / 0|Mon Jan  1 00:00:00 UTC 0001, fir:0|Mon Jan  1 00:00:00 UTC 0001, rtt(ms):0|0"}
2023-01-10T12:02:18.118Z	INFO	livekit	buffer/buffer.go:317	rtp stats	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "relayed": false, "mime": "video/vp8", "layer": 0, "direction": "upstream", "stats": "t: Tue Jan 10 12:01:02 UTC 2023|Tue Jan 10 12:02:18 UTC 2023|75.30s sn: 1675|1836, ep: 162|2.15/s, p: 162|2.15/s, l: 0|0.0/s|0.00%, b: 114335|12147.5bps|3312, f: 151|2.0/s / 2|Tue Jan 10 12:01:03 UTC 2023, d: 0|0.00/s, bd: 0|0.0bps|0, pp: 0|0.00/s, bp: 0|0.0bps|0, o: 0, c: 90000, j: 210(2344.3us)|210(2344.3us), n:0|0|0|0, pli:0|Mon Jan  1 00:00:00 UTC 0001 / 0|Mon Jan  1 00:00:00 UTC 0001, fir:0|Mon Jan  1 00:00:00 UTC 0001, rtt(ms):0|0"}
2023-01-10T12:02:18.118Z	INFO	livekit	buffer/buffer.go:317	rtp stats	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "relayed": false, "mime": "video/vp8", "layer": 1, "direction": "upstream", "stats": "t: Tue Jan 10 12:01:02 UTC 2023|Tue Jan 10 12:02:18 UTC 2023|75.29s sn: 2290|2723, ep: 434|5.76/s, p: 405|5.38/s, l: 0|0.0/s|0.00%, b: 354252|37642.3bps|8208, f: 201|2.7/s / 2|Tue Jan 10 12:01:03 UTC 2023, d: 0|0.00/s, bd: 0|0.0bps|0, pp: 29|0.39/s, bp: 7076|751.9bps|580, o: 0, c: 90000, j: 83(924.5us)|83(924.5us), n:0|0|0|0, pli:0|Mon Jan  1 00:00:00 UTC 0001 / 0|Mon Jan  1 00:00:00 UTC 0001, fir:0|Mon Jan  1 00:00:00 UTC 0001, rtt(ms):0|0"}
2023-01-10T12:02:18.120Z	INFO	livekit	rtc/mediatrackreceiver.go:526	removing all subscribers for mime	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false, "trackID": "TR_VCZKPGjdszgY55", "relayed": false, "mime": "video/vp8"}
2023-01-10T12:02:18.120Z	INFO	livekit	rtc/participant.go:1916	exiting publisher RTCP worker	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "645", "pID": "PA_2JXtd6sHJ2Ee", "remote": false}
2023-01-10T12:02:19.635Z	INFO	livekit	rtc/room.go:308	new participant joined	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "pID": "PA_cnrVPePDDE7u", "participant": "646", "protocol": 8, "options": {"AutoSubscribe":true}}
2023-01-10T12:02:19.636Z	INFO	livekit	rtc/room.go:257	participant state changed	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "state": "JOINED", "participant": "646", "pID": "PA_cnrVPePDDE7u", "oldState": "JOINING"}
2023-01-10T12:02:19.636Z	INFO	livekit	service/rtcservice.go:266	new client WS connected	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "646", "pID": "PA_cnrVPePDDE7u", "remote": false, "connID": "CO_iZctnJxS2Axx"}
2023-01-10T12:02:20.778Z	INFO	livekit	rtc/transport.go:509	selected ICE candidate pair	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "646", "pID": "PA_cnrVPePDDE7u", "remote": false, "transport": "SUBSCRIBER", "pair": "(local) udp4 host 91.250.106.15:55141 <-> (remote) udp4 prflx 91.90.163.34:57638 related :0"}
2023-01-10T12:02:20.954Z	INFO	livekit	rtc/room.go:257	participant state changed	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "state": "ACTIVE", "participant": "646", "pID": "PA_cnrVPePDDE7u", "oldState": "JOINED"}
2023-01-10T12:02:50.719Z	INFO	livekit	rtc/signalhandler.go:62	client leaving room	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "646", "pID": "PA_cnrVPePDDE7u", "remote": false}
2023-01-10T12:02:50.719Z	INFO	livekit	rtc/participant.go:614	participant closing	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "646", "pID": "PA_cnrVPePDDE7u", "remote": false, "sendLeave": true, "reason": "CLIENT_REQUEST_LEAVE"}
2023-01-10T12:02:50.719Z	INFO	livekit	service/rtcservice.go:236	finishing WS connection	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "646", "pID": "PA_cnrVPePDDE7u", "remote": false, "connID": "CO_iZctnJxS2Axx"}
2023-01-10T12:02:50.720Z	INFO	livekit	rtc/participant_signal.go:232	closing signal connection	{"room": "521501298", "roomID": "RM_nszqvmqiqThF", "participant": "646", "pID": "PA_cnrVPePDDE7u", "remote": false}
2023-01-10T12:03:10.394Z	INFO	livekit	rtc/room.go:573	closing room	{"room": "521501298", "roomID": "RM_nszqvmqiqThF"}
2023-01-10T12:03:10.395Z	INFO	livekit	service/roommanager.go:110	deleting room state	{"room": "521501298"}
2023-01-10T12:03:10.395Z	INFO	livekit	service/roommanager.go:427	room closed	{"room": "521501298", "roomID": "RM_nszqvmqiqThF"}
2023-01-10T12:17:51.550Z	INFO	livekit	server/main.go:259	exit requested, shutting down	{"signal": "terminated"}
2023-01-10T12:17:51.785Z	INFO	livekit	redis/redis.go:82	connecting to redis	{"simple": true, "addr": "localhost:6379"}
2023-01-10T12:17:52.907Z	INFO	livekit	rtc/config.go:321	failed to get external ip	{"local": "172.17.0.1", "err": "could not validate external IP"}
2023-01-10T12:17:52.907Z	INFO	livekit	rtc/config.go:321	failed to get external ip	{"local": "10.0.97.11", "err": "could not determine public IP"}
2023-01-10T12:17:52.907Z	INFO	livekit	rtc/config.go:105	using external IPs	{"ips": ["91.250.106.15/91.250.106.15", "10.0.97.11/10.0.97.11", "172.17.0.1/172.17.0.1"]}
2023-01-10T12:17:52.910Z	INFO	livekit	service/server.go:212	starting LiveKit server	{"portHttp": 7880, "nodeID": "ND_MJd5gtdO", "nodeIP": "91.250.106.15", "version": "1.3.3", "rtc.portTCP": 7881, "rtc.portICERange": [50000, 60000]}
2023-01-10T12:19:21.864Z	INFO	livekit	service/roomallocator.go:111	selected node for room	{"room": "501053874", "roomID": "RM_ShFtjXyRYM68", "selectedNodeID": "ND_MJd5gtdO"}
2023-01-10T12:19:21.866Z	INFO	livekit	rtc/room.go:308	new participant joined	{"room": "501053874", "roomID": "RM_ShFtjXyRYM68", "pID": "PA_byETqhUTJXzr", "participant": "647", "protocol": 8, "options": {"AutoSubscribe":true}}
2023-01-10T12:19:21.867Z	INFO	livekit	rtc/room.go:257	participant state changed	{"room": "501053874", "roomID": "RM_ShFtjXyRYM68", "state": "JOINED", "participant": "647", "pID": "PA_byETqhUTJXzr", "oldState": "JOINING"}
2023-01-10T12:19:21.868Z	INFO	livekit	service/rtcservice.go:266	new client WS connected	{"room": "501053874", "roomID": "RM_ShFtjXyRYM68", "participant": "647", "pID": "PA_byETqhUTJXzr", "remote": false, "connID": "CO_HWd6zQddsccc"}
2023-01-10T12:19:23.124Z	INFO	livekit	rtc/transport.go:509	selected ICE candidate pair	{"room": "501053874", "roomID": "RM_ShFtjXyRYM68", "participant": "647", "pID": "PA_byETqhUTJXzr", "remote": false, "transport": "SUBSCRIBER", "pair": "(local) tcp4 host 91.250.106.15:7881 <-> (remote) tcp4 prflx 37.140.39.213:62152 related :0"}
2023-01-10T12:19:23.343Z	INFO	livekit	rtc/participant.go:1567	pending track added	{"room": "501053874", "roomID": "RM_ShFtjXyRYM68", "participant": "647", "pID": "PA_byETqhUTJXzr", "remote": false, "trackID": "TR_AMCqLzSVatsumu", "track": "sid:\"TR_AMCqLzSVatsumu\" source:MICROPHONE", "request": "cid:\"a9f0085b-8986-482a-898a-3a33539f5adb\" source:MICROPHONE"}
2023-01-10T12:19:23.343Z	INFO	livekit	rtc/participant.go:1567	pending track added	{"room": "501053874", "roomID": "RM_ShFtjXyRYM68", "participant": "647", "pID": "PA_byETqhUTJXzr", "remote": false, "trackID": "TR_VCZ7QuyGHJmWbL", "track": "sid:\"TR_VCZ7QuyGHJmWbL\" type:VIDEO width:1280 height:720 source:CAMERA layers:{width:320 height:180 bitrate:120000} layers:{quality:MEDIUM width:640 height:360 bitrate:300000} layers:{quality:HIGH width:1280 height:720 bitrate:1700000}", "request": "cid:\"c13d3299-f5db-4a2f-9eec-4a00f9e83716\" type:VIDEO width:1280 height:720 source:CAMERA layers:{width:320 height:180 bitrate:120000} layers:{quality:MEDIUM width:640 height:360 bitrate:300000} layers:{quality:HIGH width:1280 height:720 bitrate:1700000}"}
2023-01-10T12:19:23.467Z	INFO	livekit	rtc/room.go:257	participant state changed	{"room": "501053874", "roomID": "RM_ShFtjXyRYM68", "state": "ACTIVE", "participant": "647", "pID": "PA_byETqhUTJXzr", "oldState": "JOINED"}
2023-01-10T12:19:23.860Z	INFO	livekit	rtc/transport.go:509	selected ICE candidate pair	{"room": "501053874", "roomID": "RM_ShFtjXyRYM68", "participant": "647", "pID": "PA_byETqhUTJXzr", "remote": false, "transport": "PUBLISHER", "pair": "(local) udp4 host 91.250.106.15:50802 <-> (remote) udp4 srflx 37.140.39.213:58071 related 192.168.0.105:58071"}
2023-01-10T12:19:24.013Z	INFO	livekit	sfu/streamtrackermanager.go:405	available layers changed - layer seen	{"room": "501053874", "roomID": "RM_ShFtjXyRYM68", "participant": "647", "pID": "PA_byETqhUTJXzr", "remote": false, "trackID": "TR_VCZ7QuyGHJmWbL", "relayed": false, "mime": "video/vp8", "added": 0, "availableLayers": [0], "exemptedLayers": []}
</details>

**Comment by cnderrauber** [comment]
@burzomir how do you config your turn server, does the 5349 port is opened, which proxy software you are using?

**Comment by cnderrauber** [comment]
@TheOptimisticFactory can you post your livekit-server's startup log? and the browser's candidate screenshot

**Comment by burzomir** [comment]
@cnderrauber Currently LiveKit's TURN is disabled completely because I'm trying to configure it to use our own TURN servers. Can we somehow sync up on time when it should be enabled in order to be available to you?

**Comment by cnderrauber** [comment]
@burzomir Are you in livekit's slack community? we can sync up there to investigate this

**Comment by TheOptimisticFactory** [comment]
> @TheOptimisticFactory can you post your livekit-server's startup log? and the browser's candidate screenshot

<details>
  <summary>Here is livekit-server's startup logs (click to expand)</summary>
  
  ```logtalk
  2023-01-13T10:39:05.920Z	INFO	livekit	redis/redis.go:82	connecting to redis	{"simple": true, "addr": "redis:6379"}
  2023-01-13T10:39:05.996Z	INFO	livekit	rtc/config.go:321	failed to get external ip	{"local": "10.0.0.10", "err": "write udp4 10.0.0.10:7882->108.177.15.127:19302: write: operation not permitted"}
  2023-01-13T10:39:07.011Z	DEBUG	livekit	config/ip.go:171	error reading from UDP socket	{"err": "read udp 172.18.0.5:7882: use of closed network connection"}
  2023-01-13T10:39:07.011Z	INFO	livekit	rtc/config.go:321	failed to get external ip	{"local": "172.18.0.5", "err": "could not validate external IP"}
  2023-01-13T10:39:10.992Z	INFO	livekit	rtc/config.go:321	failed to get external ip	{"local": "10.0.5.4", "err": "could not determine public IP"}
  2023-01-13T10:39:10.993Z	INFO	livekit	rtc/config.go:321	failed to get external ip	{"local": "13.0.0.5", "err": "could not determine public IP"}
  2023-01-13T10:39:10.993Z	INFO	livekit	rtc/config.go:321	failed to get external ip	{"local": "12.0.0.6", "err": "could not determine public IP"}
  2023-01-13T10:39:10.993Z	INFO	livekit	rtc/config.go:102	no external IPs found, using node IP for NAT1To1Ips	{"ip": "20.XXX.XX.103"}
  2023-01-13T10:39:10.993Z	WARN	livekit	rtc/rtc_unix.go:17	UDP receive buffer is too small for a production set-up	{"current": 425984, "suggested": 5000000}
  2023-01-13T10:39:10.994Z	INFO	livekit	service/turn.go:127	Starting TURN server	{"turn.relay_range_start": 30000, "turn.relay_range_end": 40000, "turn.portUDP": 3478}
  2023-01-13T10:39:10.994Z	INFO	livekit.tcp_mux	logger/logadapter.go:66	Listening TCP on [::]:7881
  2023-01-13T10:39:10.995Z	DEBUG	livekit	routing/redisrouter.go:413	starting redisWorker	{"nodeID": "ND_NrQajeYj"}
  2023-01-13T10:39:10.997Z	INFO	livekit	service/server.go:212	starting LiveKit server	{"portHttp": 7880, "nodeID": "ND_NrQajeYj", "nodeIP": "20.XXX.XX.103", "version": "1.3.3", "rtc.portTCP": 7881, "rtc.portUDP": 7882}
   ```
</details>

<details>
  <summary>Screenshot of the browser's candidate (chromium)</summary>

  ![image](https://user-images.githubusercontent.com/2607260/212304081-f7fad788-a712-46a2-ba05-ba8c14edf7ea.png)
  
  ![image](https://user-images.githubusercontent.com/2607260/212304274-b108c92a-752c-4526-a965-bef050be665a.png)
</details>

<details>
  <summary>Screenshot of the browser's candidate (firefox)</summary>
  
  ![image](https://user-images.githubusercontent.com/2607260/212304837-0fbd1487-f17c-40b2-a33d-96be866adaa0.png)

  ![image](https://user-images.githubusercontent.com/2607260/212305368-f5242b9c-3194-4aa5-9ae4-cec5f559d9f6.png)
</details>

**Comment by cnderrauber** [comment]
@TheOptimisticFactory It looks like your livekit-server can't get external ip address but you set the `use_external_ip` in your config file, does your server can't be accessed from public internet?

**Comment by TheOptimisticFactory** [comment]
> @TheOptimisticFactory It looks like your livekit-server can't get external ip address but you set the `use_external_ip` in your config file, does your server can't be accessed from public internet?

For someone on the internet to reach the livekit server, the request needs to pass through a proxy. The IP of that proxy is provided using `--node-ip <REDACTED_IP>` -- which cannot be detected automatically by livekit

**Comment by cnderrauber** [comment]
From the log, I see your node can't be access from outside, do you open the udp port 7882 forward to livekit-server?

**Comment by raphaelluchini** [comment]
After the update to 1.3.3, I started to have the same problem. Before 1.2.x that was not happening. :(

**Comment by burzomir** [comment]
That's interesting, on our side we also observed a pattern, that when a user enters a room for the first time it works ok, but after refreshing there is also PeerConnection timeout. I also thought it may be related to tokens. But we already generate a new identity each time.

**Comment by cnderrauber** [comment]
@raphaelluchini @burzomir That's weird if the first time connect is ok but next will failed. I tryied to reproduce it but no result in my environment. Can you described the detail steps to repro the reconnect issue? That will be a hint to the problem

**Comment by TheOptimisticFactory** [comment]
> > @TheOptimisticFactory It looks like your livekit-server can't get external ip address but you set the `use_external_ip` in your config file, does your server can't be accessed from public internet?
> 
> ~For someone on the internet to reach the livekit server, the request needs to pass through a proxy. The IP of that proxy is provided using `--node-ip <REDACTED_IP>` -- which cannot be detected automatically by livekit~

I replied a bit too hastily yielding an incorrect statement, allow me to rectify it:

- The IP provided using the option `--node-ip <REDACTED_IP>` corresponds to the public IP of the machine on which the **livekit-server** is running.

- This means the address advertised and used during the ICE and TURN process is indeed the public IP of the **livekit-server**  -- these requests do **NOT** pass through any proxy, unlike what I initially stated

Apologies for the mixup.

<sub>-- Note to self: keep away from Github when it's past 3am</sub>

**Comment by burzomir** [comment]
So the issue is easily reproducible on our side now:

1. Create a token,
2. Use that token to connect to a room,
3. PeerConnection timeout error occurs,
4. Wait around a minute,
5. Connect again with the same token,
6. Success.

As @cnderrauber  explained to me this 1 minute is required to switch from UDP to TCP in case UDP is blocked.

Could that be possible to immediately force Livekit to switch to TCP immediately when PeerConnection timeout occurs? 1 minute is quite long and hardcoding 1 minute delay on the client side isn't the best solution either, is it?

**Comment by xdef** [comment]
I encountered the same problem, I will try to reproduce it.

### Connecting with error
1. Create a token
2. Use that token to connect to a room
3. We get an error from the browser: `could not connect PeerConnection after timeout`

**Logs in the attachment**:
<details>
  <summary>chrome://webrtc-internals/</summary>
  <img src='https://user-images.githubusercontent.com/2283004/215971227-341351d5-3843-4c98-9e95-f657cd45a420.png' />
</details>

<details>
  <summary>browsers console</summary>
  <img src='https://user-images.githubusercontent.com/2283004/215971235-b77a75c2-bebb-4c7d-9ebb-a70fc4b215cf.png' />
</details>

[tcpdump on client side (Wireshark compatible)](https://github.com/livekit/livekit/files/10553957/client_error.txt)

[LiveKit logs](https://github.com/livekit/livekit/files/10553959/livekit_log_error.txt)

### Successful connection
4. Wait until the rtc session is closed on the server (around a minute):
```
...
livekit-livekit-1  | 2023-02-01T05:55:02.480Z	DEBUG	livekit	service/roommanager.go:459	RTC session finishing	{"participant": "6384f135e77755179c3a3284", "pID": "PA_5NPCdnNLm9rU", "room": "New appointment", "roomID": "RM_MPcGXj5Hjkya"}
...
```

5. Connect again with the same token
6. Success

**Logs in the attachment**:
<details>
  <summary>chrome://webrtc-internals/</summary>
  <img src='https://user-images.githubusercontent.com/2283004/215971215-1fdc7cb7-2e1b-4a88-9810-987a00c3fa1b.png' />
</details>

<details>
  <summary>browsers console</summary>
  <img src='https://user-images.githubusercontent.com/2283004/215971221-f27dae05-615e-463b-abbb-bdb3c534bdd9.png' />
</details>

[tcpdump on client side (Wireshark compatible)](https://github.com/livekit/livekit/files/10553955/client_success.txt)

[LiveKit logs](https://github.com/livekit/livekit/files/10553958/livekit_log_success.txt)

The logs show that the connection error is due to the use of the UDP protocol when establishing a connection to the TURN server.
When reconnecting in the server log we see the forced use of TCP:
```
...
livekit-livekit-1  | 2023-02-01T05:57:27.806Z	INFO	livekit	rtc/transportmanager.go:470	setting ICE config	{"room": "New appointment", "roomID": "RM_6Js87NqoQpT9", "participant": "6384f135e77755179c3a3284", "pID": "PA_Z6Wuchq8jZtz", "remote": false, "iceConfig": "preference_subscriber:ICT_TCP preference_publisher:ICT_TCP"}
...
```

We try to force the built-in turn server in tcp mode:
```
turn:
    enabled: true
    domain: livekit-turn.example.com
    tls_port: 5349
    external_tls: true
```

But Google servers are added to the iceServers configuration and the first connection also terminates with an error:
```
iceServers: [turns:livekit-turn.example.com:443?transport=tcp, stun:stun.l.google.com:19302, stun:stun1.l.google.com:19302]
```

<details>
  <summary>Webrtc internal</summary>
  <img src='https://user-images.githubusercontent.com/2283004/215971237-f86b049d-9c14-4bef-a6b1-1aed20f9b488.png' />
</details>

**Comment by davidzhao** [comment]
@xdef in order to avoid using the default Google STUN servers, you'll need to provide one of the following:
* set [rtc.turn_servers](https://github.com/livekit/livekit/blob/master/config-sample.yaml#L58)
* set [rtc.stun_servers](https://github.com/livekit/livekit/blob/master/config-sample.yaml#L55)
* enable turn.udp_port

TURN/TLS cannot be used to replace a STUN server.

**Comment by burzomir** [comment]
@cnderrauber @davidzhao I deployed livekit-server@1.3.4 to our server and it works great right now. Thank you for handling this issue 🙂

**Comment by davidzhao** [comment]
Thanks for the confirmation @burzomir ! I'm glad that it's been resolved for you.

**Comment by bell-101** [comment]
Hey @burzomir! I have the same problem (first connection closed by timeout, second with same token - success)? What is your solution? I tried 1.3.4 version, but no effects

**Comment by nkonev** [comment]
Hmm, I also wrapped room.connect() by [retry](https://www.npmjs.com/package/@lifeomic/attempt) https://github.com/nkonev/videochat/blob/db7a82af87ea46e921e6cc74d4ff225c796e5304/frontend/src/ChatVideo.vue#L328

Wanna say, that it won't connect every time, roughly, 1/10 attempts fails, so I added retry

**Comment by raphaelluchini** [comment]
Unfortunately, we are still facing this issue, kind of 1/10 number from what @nkonev mentioned, and there's nothing relevant in the logs that indicates the issue :/.

**Comment by bell-101** [comment]
@burzomir, @nkonev, @raphaelluchini thanks, guys. In my case, absolutely every first connection fails with a timeout error :((

**Comment by burzomir** [comment]
@bell-101 Probably you are unable to connect via UDP (blocked or something). It fails for the first time but livekit-server remembers that for a given token and on the next try it should use TCP which should work better.

**Comment by bell-101** [comment]
@burzomir yep, there is a problem with udp. I have set the log level to debug and see this:

`livekit-livekit-1  | 2023-02-16T19:09:07.385Z	DEBUG	livekit	config/ip.go:171	error reading from UDP socket	{"err": "read udp 172.17.0.1:55813: use of closed network connection"}`

but i don't understand, why? I don't have any firewalls etc and my vps

**Comment by cnderrauber** [comment]
@bell-101 Maybe your ISP has blocked udp protocol used by webrtc (stun/dtls), so the first connection try will fail then livekit-server detects it and switch to tcp, so the second try worked. You can add retry to your application so your user can connect without retry manually.

**Comment by raphaelluchini** [comment]
I could suggest having a better error log description (I saw some improvements already) and error responses when a connection fails + a built-in retry mechanism in the JS SDK.

**Comment by cnderrauber** [comment]
The js-sdk will support auto retry at initial connection in future release.
