### ISSUE TITLE
LiveKit 1.8.3 high CPU usage

### ISSUE THREAD

**Issue by serhiynovos** [livekit/livekit#3316]
In one of my environment I installed livekit 1.8.3 and noticed that with some time I have high CPU usage, about 4 CPU cores. When I rolled back to 1.8.0 max what I saw it was 0.4 CPU for the same streams.

Together with livekit server I have running ingress 1.4.0 and egress 1.9.0

**Comment by boks1971** [comment]
Would you happen to have a profile with 1.8.3 @serhiynovos ? 🙏

**Comment by serhiynovos** [comment]
@boks1971 Can you please tell me how can I get profile in kubernetes environment ?

**Comment by boks1971** [comment]
I think there should be a `/debug/pprof` endpoint. If you are using kube, you can use something like Lens (https://k8slens.dev/) to port forward the signalling port (7880 by default) to some port on your local machine and open it on your local machine. Let us say you port forward to 22222, you can then open `http://localhost:22222/debug/pprof` and see a listing like the attached screenshot. You can click on `profile`. It will collect profile for 30 seconds and download the file.

<img width="1377" alt="Screenshot 2025-01-08 at 9 21 35 PM" src="https://github.com/user-attachments/assets/bbff88e7-77b3-45b3-9bd8-48c9cc544fee" />

**Comment by serhiynovos** [comment]
@boks1971 I did port forwarding. It returns 404 error. 
<img width="1713" alt="Screenshot 2025-01-08 at 18 02 44" src="https://github.com/user-attachments/assets/002a36cc-e692-4b02-bd27-29d9971335ec" />

**Comment by boks1971** [comment]
Does just loading `http://localhost:7880` return `OK`? Also, just confirming that you forwarded 7880 -> 7880?

**Comment by serhiynovos** [comment]
Yes. I can access. Based on this code https://github.com/livekit/livekit/blob/4016e3dc5aa14c028d40d01dd4f42a52fc977d68/cmd/server/main.go#L103 I have to enable dev mode

**Comment by serhiynovos** [comment]
> Yes. I can access. Based on this code
> 
> https://github.com/livekit/livekit/blob/4016e3dc5aa14c028d40d01dd4f42a52fc977d68/cmd/server/main.go#L103
> 
> I have to enable dev mode

@boks1971 In dev mode it works. Let me check profile next time when I'll notice CPU spike

**Comment by holzgeist** [comment]
Hi @boks1971 
I'm having the same issue, here is a profile gathered like you described above: [profile.zip](https://github.com/user-attachments/files/18492623/profile.zip)

It happened when a client switched from WIFI to mobile data, i.e. had to reconnect everything. It looks like the server goes into a busy loop for a few minutes and then recovers. 

This is the log with debug level during the call: [log-ip-redacted.log](https://github.com/user-attachments/files/18492757/log-ip-redacted.log)

I hope this helps and let me know if you need any more data

**Comment by holzgeist** [comment]
Updates:
Looks like the busy loop is in pion/ice, and v1.8.3 did a major update from v2 to v4 of this lib: https://github.com/livekit/livekit/commit/54f9f7de51a2404171bd6dad4f96ae115890dd10

https://github.com/pion/ice/issues/742 appears to be a good candidate, but it was fixed in 4.0.3, which is included in livekit 1.8.3.

**Comment by boks1971** [comment]
@holzgeist  Is it reproducible for you under those conditions? Not seeing anything interesting in the logs. Profile shows sycall and GC taking most of the time. But, no clear indication of a hot spot. Will look more.

Yeah, this release did get the major Pion update, but have not been able to tie it to this yet.

**Comment by holzgeist** [comment]
Unfortunately it's not 100% reproducible

**Comment by serhiynovos** [comment]
[profile.zip](https://github.com/user-attachments/files/18592402/profile.zip)

Hi I just now noticed this behaviour. For me it happens when I try to start participant recording and this participant is using VP9 codec

**Comment by boks1971** [comment]
Thank you @serhiynovos . Still not seeing anything that stands out in the profile :-( 

Is it consistent for you? If yes, we can try reproducing it with that combination and debug further.

**Comment by serhiynovos** [comment]
@boks1971 Unfortunately I cannot reproduce exact steps to make CPU spike. Currently I'm trying to reproduce what I was doing before but I only see 0.2 CPU core usage

**Comment by serhiynovos** [comment]
> I think there should be a `/debug/pprof` endpoint. If you are using kube, you can use something like Lens (https://k8slens.dev/) to port forward the signalling port (7880 by default) to some port on your local machine and open it on your local machine. Let us say you port forward to 22222, you can then open `http://localhost:22222/debug/pprof` and see a listing like the attached screenshot. You can click on `profile`. It will collect profile for 30 seconds and download the file.
> 
> <img alt="Screenshot 2025-01-08 at 9 21 35 PM" width="1377" src="https://private-user-images.githubusercontent.com/6278212/401212445-bbff88e7-77b3-45b3-9bd8-48c9cc544fee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgyNjA3MDgsIm5iZiI6MTczODI2MDQwOCwicGF0aCI6Ii82Mjc4MjEyLzQwMTIxMjQ0NS1iYmZmODhlNy03N2IzLTQ1YjMtOWJkOC00OGM5Y2M1NDRmZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMzBUMTgwNjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRkZDY0YjUxOTJhZDg0MDUzYzUxZTA3OTRiZGQxNzBjZGJmYjZmNmExNDI5NDk5NWRkMWQ2NjNmYWJmYzc4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SRujozShOUeQqYQUmvM_Rq6nBXPUGt-_4CzWzW3JrAY">

@boks1971 can I try something else from the list when I see spike next time ?

**Comment by boks1971** [comment]
Some possible options. Would any of these work in your environment?
1. Try setting up Pyroscope for continuous profiling - https://pyroscope.io/
2. Do it programatically like here using `StartCPUProfile` and `StopCPUProfile` - https://pkg.go.dev/runtime/pprof#hdr-Profiling_a_Go_program. Basically, do continuous profiling in code. Maybe, run this in 30 second/1 minute chunks and if CPU hits a high, self kill the server after the current profile collection ends and hopefully that window would have caught the CPU spike.

**Comment by baptisteidruide** [comment]
Did you fix it in 1.8.4

**Comment by holzgeist** [comment]
Some more data points:
* it looks like this behavior starts when livekit was running for a while (a few days?) for us
* in the simplest case, just two participants connected, none of them published/subscribed any tracks and according to `top` CPU was at 25% on a 2 core machine, so it was using half a CPU. This is weird
* even weirder, the captured profile (with `/debug/pprof/profile?seconds=30`) doesn't show any CPU consumption [report.zip](https://github.com/user-attachments/files/20189355/report.zip) (like 40ms usage in 30s)
* high CPU usage starts right after call start and lasts ~1min longer than the call
* This is running on 1.8.4 with a (very likely very unrelated) [patch](https://github.com/holzgeist/livekit/commit/99ffb468d3892038258306a9ce3eb6969a8f1289) applied

Several test calls:
![Image](https://github.com/user-attachments/assets/a054d09c-7670-41ad-9379-2b73e2cca6e1)

Test call with logs attached: 

![Image](https://github.com/user-attachments/assets/64497678-546e-493b-8961-46fdf795b9d9)

[report.log](https://github.com/user-attachments/files/20189569/report.log)


Is there anything I should log/trace while I have a 100% reproducible server running? @boks1971

**Comment by boks1971** [comment]
That's a puzzler @holzgeist . Nothing in the logs or profile suggests anything that should take that much CPU.

But, the one minute may be a clue. We clean up analytics stats worker for a participant after [three minutes](https://github.com/livekit/livekit/blob/0a5f3c2ae60b682389dba0399b299a3879be87eb/pkg/telemetry/telemetryservice.go#L91). Can't think of anything that happens one minute later.

I will check more. I think I also see high reported load when running on dev machine even when the server is completely idle. And I am running it directly on a Mac, not even using Docker. Not sure what causes it to report high load. You have seen `top` show it too on a server. So, there is something that is mis-behaving, just too hard to catch it.

Maybe capturing a few more profiles to see if you can catch one in the act?

**Comment by boks1971** [comment]
Thank you @holzgeist . Given that profile, that issue seems like the most plausible candidate. However, like you mentioned a version with the fix should be used in the server. Hopefully, pion logs will show more 🤞

**Comment by boks1971** [comment]
oh yeah, that would definitely cause trouble. Yeah, that looks like CNI. Maybe `Calico`? (https://docs.tigera.io/calico/latest/getting-started/kubernetes/hardway/install-cni-plugin). Why is it trying to listen on CNI interface?

Can you try only including interfaces exposed to the outside world or try excluding this CNI interface? https://github.com/livekit/mediatransportutil/blob/5f8c73435f62a99980b5140bbf026d8d9a5425a0/pkg/rtcconfig/config.go#L52

**Comment by holzgeist** [comment]
I browsed through the logs a bit more. It looks like this is a non-existing interface (which explains the `invalid argument` error).
It belonged to another pod that was stopped for completely unrelated reasons.
Maybe `ice` doesn't reload interfaces often enough?

**Comment by holzgeist** [comment]
I'll try if I can reproduce the issue this way and then check by pinning the interfaces.

**Comment by boks1971** [comment]
> I browsed through the logs a bit more. It looks like this is a non-existing interface (which explains the `invalid argument` error). It belonged to another pod that was stopped for completely unrelated reasons. Maybe `ice` doesn't reload interfaces often enough?

I do not know if it refreshes periodically. It might be doing only once.

**Comment by holzgeist** [comment]
I could reproduce it by restarting a random pod (which removes its interface). This causes livekit/ice high CPU usage.
That's why the problem occurs/gets worse over time, because more and more services restart, causing more interfaces to go missing

I'll file a bug in pion/ice

**Comment by holzgeist** [comment]
This still not explains, why it even tries to listen to the CNI of another container though

**Comment by boks1971** [comment]
Great find @holzgeist . 

It tries to find local interfaces and it is somehow seeing that interface.

**Comment by holzgeist** [comment]
To make UDP work, we use `host_network: true`. This is why it sees all interfaces

**Comment by holzgeist** [comment]
Pinning the interface works 🎉

**Comment by serhiynovos** [comment]
@boks1971 I'm running it now in k3s with Flannel. In logs I see it's also sending ICE for Flannel ip addresses. 

The issue where I was exeprienced it most it was RKE2 with Cilium CNI. Let me also start egress. I think it happens when egress tries to communicate with livekit and they try to use CNI network for it

```
2025-05-14T19:09:15.826Z	DEBUG	livekit	rtc/participant_signal.go:278	sending ICE candidate	{"room": "027de6d9-848b-41a2-8946-66928a0f3d91-view_mode-68205b44a977abce7d0e1466", "roomID": "RM_gCtmivVEhCrw", "participant": "user_1747249755786", "pID": "PA_zABe42u2Kn7V", "remote": false, "transport": "SUBSCRIBER", "trickle": {"candidateInit": "{\"candidate\":\"candidate:2354437776 1 udp 2130706431 192.168.0.98 58591 typ host\",\"sdpMid\":\"\",\"sdpMLineIndex\":0,\"usernameFragment\":null}", "target": "SUBSCRIBER"}}
2025-05-14T19:09:15.827Z	DEBUG	livekit	rtc/participant_signal.go:278	sending ICE candidate	{"room": "027de6d9-848b-41a2-8946-66928a0f3d91-view_mode-68205b44a977abce7d0e1466", "roomID": "RM_gCtmivVEhCrw", "participant": "user_1747249755786", "pID": "PA_zABe42u2Kn7V", "remote": false, "transport": "SUBSCRIBER", "trickle": {"candidateInit": "{\"candidate\":\"candidate:833007472 1 tcp 1671430143 192.168.0.98 7881 typ host tcptype passive\",\"sdpMid\":\"\",\"sdpMLineIndex\":0,\"usernameFragment\":null}", "target": "SUBSCRIBER"}}
2025-05-14T19:09:15.827Z	DEBUG	livekit	rtc/participant_signal.go:278	sending ICE candidate	{"room": "027de6d9-848b-41a2-8946-66928a0f3d91-view_mode-68205b44a977abce7d0e1466", "roomID": "RM_gCtmivVEhCrw", "participant": "user_1747249755786", "pID": "PA_zABe42u2Kn7V", "remote": false, "transport": "SUBSCRIBER", "trickle": {"candidateInit": "{\"candidate\":\"candidate:2162445832 1 udp 2130706431 10.42.3.0 53587 typ host\",\"sdpMid\":\"\",\"sdpMLineIndex\":0,\"usernameFragment\":null}", "target": "SUBSCRIBER"}}
2025-05-14T19:09:15.827Z	DEBUG	livekit	rtc/participant_signal.go:278	sending ICE candidate	{"room": "027de6d9-848b-41a2-8946-66928a0f3d91-view_mode-68205b44a977abce7d0e1466", "roomID": "RM_gCtmivVEhCrw", "participant": "user_1747249755786", "pID": "PA_zABe42u2Kn7V", "remote": false, "transport": "SUBSCRIBER", "trickle": {"candidateInit": "{\"candidate\":\"candidate:1024933864 1 tcp 1671430143 10.42.3.0 7881 typ host tcptype passive\",\"sdpMid\":\"\",\"sdpMLineIndex\":0,\"usernameFragment\":null}", "target": "SUBSCRIBER"}}
2025-05-14T19:09:15.827Z	DEBUG	livekit	rtc/participant_signal.go:278	sending ICE candidate	{"room": "027de6d9-848b-41a2-8946-66928a0f3d91-view_mode-68205b44a977abce7d0e1466", "roomID": "RM_gCtmivVEhCrw", "participant": "user_1747249755786", "pID": "PA_zABe42u2Kn7V", "remote": false, "transport": "SUBSCRIBER", "trickle": {"candidateInit": "{\"candidate\":\"candidate:3179571128 1 udp 2130706431 10.42.3.1 56850 typ host\",\"sdpMid\":\"\",\"sdpMLineIndex\":0,\"usernameFragment\":null}", "target": "SUBSCRIBER"}}
```

**Comment by boks1971** [comment]
Thank you @serhiynovos . I think if the interface is there, it looks like it should work fine. 

What happened with @holzgeist is that it seemed to used a non-existent interface.

If you can reproduce it, can you also try the interface pinning here (https://github.com/livekit/mediatransportutil/blob/5f8c73435f62a99980b5140bbf026d8d9a5425a0/pkg/rtcconfig/config.go#L52). You can exclude an interface or even CIDRs to limit usage.

**Comment by serhiynovos** [comment]
> Thank you [@serhiynovos](https://github.com/serhiynovos) . I think if the interface is there, it looks like it should work fine.
> 
> What happened with [@holzgeist](https://github.com/holzgeist) is that it seemed to used a non-existent interface.
> 
> If you can reproduce it, can you also try the interface pinning here (https://github.com/livekit/mediatransportutil/blob/5f8c73435f62a99980b5140bbf026d8d9a5425a0/pkg/rtcconfig/config.go#L52). You can exclude an interface or even CIDRs to limit usage.

@boks1971 Seams like it can be CNI specific error.  For interface config I can just use include section, right ?

**Comment by boks1971** [comment]
Yes, you can just use the `Includes` section and just specify interfaces exposed to the external world @serhiynovos

**Comment by serhiynovos** [comment]
@boks1971  Tried on another k8s cluster with Cilium CNI. I had one room with 1 video publisher and one subscriber which should not create any load on LiveKit server. During the session I was restarting different pods. 

I did not see logs like this
```
2025-05-14T07:19:52.976Z        DEBUG   livekit.transport.pion.ice      v4@v4.0.7/net.go:160    Failed to listen [REDACTED_IPV6_ADDRESS%cali156091a92e0]:0: listen udp [REDACTED_IPV6_ADDRESS%cali156091a92e0]:56095: bind: invalid argument  {"room": "1224056673", "roomID": "RM_iYmYNLFkWqTq", "participant": "1725878616", "pID": "PA_Zp2cJ8uvefnc", "remote": false, "transport": "PUBLISHER"}
```

But I started seeing bunch of errors

```
2025-05-15T08:58:11.762Z	DEBUG	livekit.sub	rtpstats/rtpstats_sender.go:570	error getting rtt	{"room": "d49ca9d6-424f-408b-9250-9ea0b8d8ab9a-view_mode-6825a98342aa1b87de044360", "roomID": "RM_PmnXeQi2sx7w", "participant": "user_1747299481016", "pID": "PA_fevje88fK5rB", "remote": false, "trackID": "TR_VCrCtSwvknvAJj", "relayed": false, "subscriberID": "PA_fevje88fK5rB:1747299483637816891", "error": "not last sender report, lastSR: 0x2b204a4c, received: 0x2b1d5ade"}
2025-05-15T08:58:11.770Z	DEBUG	livekit.sub	rtpstats/rtpstats_sender.go:570	error getting rtt	{"room": "d49ca9d6-424f-408b-9250-9ea0b8d8ab9a-view_mode-6825a98342aa1b87de044360", "roomID": "RM_PmnXeQi2sx7w", "participant": "user_1747299481016", "pID": "PA_fevje88fK5rB", "remote": false, "trackID": "TR_VCS9Lyi35AqBSN", "relayed": false, "subscriberID": "PA_fevje88fK5rB:1747299483638060157", "error": "not last sender report, lastSR: 0x2b206163, received: 0x2b1d2c64"}
2025-05-15T08:58:14.671Z	DEBUG	livekit.sub	rtpstats/rtpstats_sender.go:570	error getting rtt	{"room": "d49ca9d6-424f-408b-9250-9ea0b8d8ab9a-view_mode-6825a98342aa1b87de044360", "roomID": "RM_PmnXeQi2sx7w", "participant": "user_1747299481016", "pID": "PA_fevje88fK5rB", "remote": false, "trackID": "TR_VCrCtSwvknvAJj", "relayed": false, "subscriberID": "PA_fevje88fK5rB:1747299483637816891", "error": "not last sender report, lastSR: 0x2b236446, received: 0x2b204a4c"}
```

In this case after room was finished CPU got to normal state

**Comment by boks1971** [comment]
It should be `includes` (plural)
```
interfaces:
  includes:
    - ens18
```

**Comment by Kevoting** [comment]
This issue continues to occur even in 1.9.0. With fewer than 5 clients connected, it uses more CPU, does not happen in version 1.8.0
In my case, I'm only using a single instance of LiveKit for testing. With 5 clients connected with UDP audio only, the CPU usage is at 15% with 4 cores.

**Comment by boks1971** [comment]
Do you have a profile to analyse please?

**Comment by DeoLeung** [comment]
similar issue with `1.9.1`, on my 16c ecs i see 300% on my docker cpu usage, any special instructions i can follow to profile or fix by config, and maybe optimize something from client side? here are some logs during spike, 
```bash
docker-livekit-1             261.61%   182.2MiB / 31.09GiB
```
```bash
livekit-1  | 2025-09-09T09:28:44.089Z   WARN    livekit.transport       rtc/transport.go:1127   error reading data channel      {"room": "roon_name", "roomID": "RM_AKRpWqZ27spe", "participant": "agent-AJ_cLAfcwr3M7wZ", "pID": "PA_tbsQnUECZzHc", "remote": false, "transport": "SUBSCRIBER", "label": "_reliable", "error": "[0xc0030681e0] abort chunk, with following errors: (User Initiated Abort: Close called)"}
livekit-1  | 2025-09-09T09:28:44.089Z   WARN    livekit.transport       rtc/transport.go:1127   error reading data channel      {"room": "roon_name", "roomID": "RM_AKRpWqZ27spe", "participant": "agent-AJ_cLAfcwr3M7wZ", "pID": "PA_tbsQnUECZzHc", "remote": false, "transport": "SUBSCRIBER", "label": "_lossy", "error": "[0xc0030681e0] abort chunk, with following errors: (User Initiated Abort: Close called)"}
livekit-1  | 2025-09-09T09:28:44.089Z   WARN    livekit.transport       rtc/transport.go:1127   error reading data channel      {"room": "roon_name", "roomID": "RM_AKRpWqZ27spe", "participant": "agent-AJ_AMtq5ztJVzHz", "pID": "PA_VNL2SKTVcHS9", "remote": false, "transport": "SUBSCRIBER", "label": "_lossy", "error": "[0xc0042b65a0] abort chunk, with following errors: (User Initiated Abort: Close called)"}
livekit-1  | 2025-09-09T09:28:44.089Z   WARN    livekit.transport       rtc/transport.go:1127   error reading data channel      {"room": "roon_name", "roomID": "RM_AKRpWqZ27spe", "participant": "agent-AJ_AMtq5ztJVzHz", "pID": "PA_VNL2SKTVcHS9", "remote": false, "transport": "SUBSCRIBER", "label": "_reliable", "error": "[0xc0042b65a0] abort chunk, with following errors: (User Initiated Abort: Close called)"}
livekit-1  | 2025-09-09T09:28:59.370Z   INFO    livekit.transport       rtc/transportmanager.go:66      short ice connection    {"room": "roon_name", "roomID": "RM_AKRpWqZ27spe", "participant": "agent-AJ_cLAfcwr3M7wZ", "pID": "PA_tbsQnUECZzHc", "remote": false, "transport": "SUBSCRIBER", "subscriberCandidates": ["[local][trickle] tcp4 host my_ip:7881 (resolved: my_ip:7881)", "[local][selected:1][trickle] udp4 host my_ip:33181 (resolved: my_ip:33181)", "[local][trickle] udp4 host 172.17.0.1:46050 (resolved: 172.17.0.1:46050)", "[local][trickle] tcp4 host 172.17.0.1:7881 (resolved: 172.17.0.1:7881)", "[remote][selected:1][trickle] udp4 host 172.20.0.4:48266", "[remote][trickle] udp4 srflx my_ip..:48266  related 172.20.0.4:48266", "[remote][trickle] tcp4 host 172.20.0.4:34101", "[remote][trickle] tcp4 host 172.20.0.4:54407"], "connectionType": "udp"}
livekit-1  | 2025-09-09T09:28:59.408Z   INFO    livekit.transport       rtc/transportmanager.go:66      short ice connection    {"room": "roon_name", "roomID": "RM_AKRpWqZ27spe", "participant": "agent-AJ_AMtq5ztJVzHz", "pID": "PA_VNL2SKTVcHS9", "remote": false, "transport": "SUBSCRIBER", "subscriberCandidates": ["[local][selected:1][trickle] udp4 host my_ip:47275 (resolved: my_ip:47275)", "[local][trickle] tcp4 host my_ip:7881 (resolved: my_ip:7881)", "[local][trickle] udp4 host 172.17.0.1:41118 (resolved: 172.17.0.1:41118)", "[local][trickle] tcp4 host 172.17.0.1:7881 (resolved: 172.17.0.1:7881)", "[remote][selected:1][trickle] udp4 host 172.20.0.4:34684", "[remote][trickle] udp4 srflx my_ip..:34684  related 172.20.0.4:34684", "[remote][trickle] tcp4 host 172.20.0.4:53947", "[remote][trickle] tcp4 host 172.20.0.4:52377"], "connectionType": "udp"}
livekit-1  | 2025-09-09T09:29:16.493Z   INFO    livekit.transport       rtc/transport.go:2756   recovering from client negotiation state on ICE restart {"room": "roon_name", "roomID": "RM_V7ohNL9fk8E5", "participant": "34", "pID": "PA_HxQiTXZcdKRf", "remote": false, "transport": "SUBSCRIBER"}
livekit-1  | 2025-09-09T09:30:01.451Z   INFO    livekit.transport       rtc/transport.go:2756   recovering from client negotiation state on ICE restart {"room": "roon_name", "roomID": "RM_V7ohNL9fk8E5", "participant": "34", "pID": "PA_SMUsBMtLdjzH", "remote": false, "transport": "SUBSCRIBER"}
livekit-1  | 2025-09-09T09:31:54.024Z   INFO    livekit.transport       rtc/transport.go:2756   recovering from client negotiation state on ICE restart {"room": "roon_name", "roomID": "RM_V7ohNL9fk8E5", "participant": "34", "pID": "PA_gDWhi5M3eSHf", "remote": false, "transport": "SUBSCRIBER"}
```

my config
```yaml
port: 7880
log_level: info
rtc:
  tcp_port: 7881
  port_range_start: 30000
  port_range_end: 50000
  # use_external_ip should be set to true for most cloud environments where
  # the host has a public IP address, but is not exposed to the process.
  # LiveKit will attempt to use STUN to discover the true IP, and advertise
  # that IP with its clients
  use_external_ip: true
redis:
  address: localhost:6379
  username: default
  password: abcdefg
  db: 2
keys:
  abcdefg
turn:
  enabled: true
  udp_port: 3478
```
and docker compose
```yaml
  livekit:
    <<: *default-base
    image: ${REGISTRY}/livekit/livekit-server:${LIVEKIT_VERSION}
    network_mode: host
    depends_on:
      - redis
    volumes:
      - /mnt/livekit:/mnt/livekit
    command: --bind 0.0.0.0 --node-ip xxxx --config /mnt/livekit/config.yaml
```

**Comment by boks1971** [comment]
This comment and a few comments after this have info on profiling - https://github.com/livekit/livekit/issues/3316#issuecomment-2578017742

**Comment by DeoLeung** [comment]
not very familiar with the network/debugging concept, but too many interfaces may sound like the cause
```shell
// yes actually quite a lot of interfaces
ip addr
```
follow config, i added
```yaml
rtc:
  interfaces:
      includes:
        - eth0
      excludes:
        - docker0
```

will monitor it a few days to c if it actually improves

**Comment by biglittlebigben** [comment]
Do you still have the issue after the change above? If so, could you provide the requested profiling?

**Comment by DeoLeung** [comment]
> Do you still have the issue after the change above? If so, could you provide the requested profiling?

havn't seen the problem for a while, i think fixing the interface works

**Comment by biglittlebigben** [comment]
Thanks!
