### ISSUE TITLE
Lots and lots of race conditions

### ISSUE THREAD

**Issue by msackman** [livekit/livekit#603]
**Describe the bug**
building and running the server with `-race` reveals a lot of race conditions going on.

**Server**
- Version: 0.15.6
- Environment: local dev

**Client**
- SDK: flutter
- Version: 0.5.6

**To Reproduce**
1. build the server with -race
2. two clients are connected to room (one can be the go server sdk)
3. See error

**Expected behavior**
No race conditions should occur

**Screenshots**
Lots. E.g.

```
==================
WARNING: DATA RACE
Write at 0x00c005dda910 by goroutine 114:
github.com/livekit/livekit-server/pkg/rtc.(*MediaTrack).ToProto()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/mediatrack.go:103 +0xa6
github.com/livekit/livekit-server/pkg/rtc.(*UpTrackManager).ToProto()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/uptrackmanager.go:76 +0x1c1
github.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).ToProto()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/participant.go:360 +0x698
github.com/livekit/livekit-server/pkg/rtc.ToProtoParticipants()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/utils.go:51 +0xdd
github.com/livekit/livekit-server/pkg/rtc.(*Room).broadcastParticipantState()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/room.go:705 +0x93
github.com/livekit/livekit-server/pkg/rtc.(*Room).onTrackPublished()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/room.go:592 +0x84
github.com/livekit/livekit-server/pkg/rtc.(*Room).onTrackPublished-fm()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/room.go:590 +0x6d
github.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).handleTrackPublished()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/participant.go:1405 +0xa3
github.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).mediaTrackReceived()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/participant.go:1393 +0x484
github.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).onMediaTrack()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/participant.go:920 +0xce
github.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).onMediaTrack-fm()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/participant.go:910 +0x4d
github.com/pion/webrtc/v3.(*PeerConnection).onTrack·dwrap·70()
/home/matthew/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.27/peerconnection.go:459 +0x58

Previous read at 0x00c005dda910 by goroutine 111:
reflect.Value.Bool()
/nix/store/j8zd71jnc6r7lhh45jwk9ywygr4w68c9-go-1.17.8/share/go/src/reflect/value.go:285 +0x51
google.golang.org/protobuf/internal/impl.fieldInfoForScalar.func1()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/message_reflect_field.go:286 +0x28f
google.golang.org/protobuf/internal/impl.(*messageState).Range()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/message_reflect_gen.go:48 +0x21e
google.golang.org/protobuf/internal/order.RangeFields()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/order/range.go:50 +0x21a
google.golang.org/protobuf/encoding/protojson.encoder.marshalMessage()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/encoding/protojson/encode.go:223 +0x452
google.golang.org/protobuf/encoding/protojson.encoder.marshalSingular()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/encoding/protojson/encode.go:304 +0x6c8
google.golang.org/protobuf/encoding/protojson.encoder.marshalValue()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/encoding/protojson/encode.go:248 +0x18f
google.golang.org/protobuf/encoding/protojson.encoder.marshalMessage.func1()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/encoding/protojson/encode.go:232 +0x213
google.golang.org/protobuf/internal/order.RangeFields()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/order/range.go:60 +0x3d9
google.golang.org/protobuf/encoding/protojson.encoder.marshalMessage()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/encoding/protojson/encode.go:223 +0x452
google.golang.org/protobuf/encoding/protojson.MarshalOptions.marshal()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/encoding/protojson/encode.go:136 +0x1cb
google.golang.org/protobuf/encoding/protojson.MarshalOptions.Marshal()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/encoding/protojson/encode.go:110 +0xa4
google.golang.org/protobuf/encoding/protojson.Marshal()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/encoding/protojson/encode.go:39 +0xa5
github.com/livekit/protocol/webhook.(*notifier).Notify()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.12.0/webhook/notifier.go:50 +0x73
github.com/livekit/livekit-server/pkg/telemetry.(*telemetryServiceInternal).notifyEvent.func1()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/telemetry/telemetryserviceinternalevents.go:278 +0x8f
github.com/gammazero/workerpool.worker()
/home/matthew/go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:243 +0x34
github.com/gammazero/workerpool.startWorker·dwrap·6()
/home/matthew/go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:234 +0x39
```

In general, there seem to be a lot involving how protobuf msgs are constructed.

```
==================
WARNING: DATA RACE
Write at 0x00c005dda928 by goroutine 114:
github.com/livekit/livekit-server/pkg/rtc.(*MediaTrack).ToProto()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/mediatrack.go:111 +0x217
github.com/livekit/livekit-server/pkg/rtc.(*MediaTrackSubscriptions).AddSubscriber()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/mediatracksubscriptions.go:270 +0x153c
github.com/livekit/livekit-server/pkg/rtc.(*MediaTrackReceiver).AddSubscriber()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/mediatrackreceiver.go:198 +0x3d4
github.com/livekit/livekit-server/pkg/rtc.(*MediaTrack).AddSubscriber()
<autogenerated>:1 +0x77
github.com/livekit/livekit-server/pkg/rtc.(*UpTrackManager).AddSubscriber()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/uptrackmanager.go:127 +0x67b
github.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).AddSubscriber()
<autogenerated>:1 +0xb9
github.com/livekit/livekit-server/pkg/rtc.(*Room).onTrackPublished()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/room.go:615 +0x745
github.com/livekit/livekit-server/pkg/rtc.(*Room).onTrackPublished-fm()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/room.go:590 +0x6d
github.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).handleTrackPublished()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/participant.go:1405 +0xa3
github.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).mediaTrackReceived()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/participant.go:1393 +0x484
github.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).onMediaTrack()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/participant.go:920 +0xce
github.com/livekit/livekit-server/pkg/rtc.(*ParticipantImpl).onMediaTrack-fm()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/rtc/participant.go:910 +0x4d
github.com/pion/webrtc/v3.(*PeerConnection).onTrack·dwrap·70()
/home/matthew/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.27/peerconnection.go:459 +0x58

Previous read at 0x00c005dda928 by goroutine 129:
google.golang.org/protobuf/internal/impl.pointer.Elem()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/pointer_unsafe.go:119 +0x3f7
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/encode.go:136 +0x3a9
google.golang.org/protobuf/internal/impl.appendMessageSliceInfo()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/codec_field.go:485 +0x20e
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/encode.go:139 +0x482
google.golang.org/protobuf/internal/impl.appendMessageSliceInfo()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/codec_field.go:485 +0x20e
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/encode.go:139 +0x482
google.golang.org/protobuf/internal/impl.appendMessageInfo()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/codec_field.go:238 +0x190
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOneofFieldCoders.func4()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/codec_field.go:96 +0x105
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer()
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshal()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/encode.go:107 +0xd0
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshal-fm()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/encode.go:100 +0xd4
google.golang.org/protobuf/proto.MarshalOptions.marshal()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/proto/encode.go:163 +0x3b9
google.golang.org/protobuf/proto.Marshal()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/proto/encode.go:79 +0x59
github.com/livekit/livekit-server/pkg/service.(*WSSignalConnection).WriteResponse()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/service/wsprotocol.go:84 +0x105
github.com/livekit/livekit-server/pkg/service.(*RTCService).ServeHTTP.func2()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v0.15.6/pkg/service/rtcservice.go:230 +0x4d4
```

There's not a shortage of them.

Data races can lead to unexpected behaviour and very hard to debug problems. These should all be solved, most likely by judiciously adding mutexes, or using atomics.

**Comment by CensorKao** [comment]
@davidliu 
There are a lot of these error messages:
`ERROR	livekit.pc	v3@v3.1.27/peerconnection.go:1582	Incoming unhandled RTP ssrc`

I do not know under what scenario will this error reported. The user will not receive the offer and thus the session will fail. Now the problem is that the success rate is low. We have also checked the client logs, and the main reason is that users cannot receive the offer.

**Comment by davidzhao** [comment]
@CensorKao this is a very different issue, your comment is describing something else. It'd be best if you can file a new issue with the appropriate details including repro steps.

**Comment by CensorKao** [comment]
@davidliu Thanks, It's hard to have repro steps. I agree with what you said, it is caused by data competition, and suddenly participants will fail to receive offers in a certain period of time. Next we'll take a closer look at the client logs to see if we can find any clues.

**Comment by CensorKao** [comment]
> @CensorKao this is a very different issue, your comment is describing something else. It'd be best if you can file a new issue with the appropriate details including repro steps.

Sorry, Wrong place! I already moved to my issues. [https://github.com/livekit/livekit-server/issues/602](url)

**Comment by davidzhao** [comment]
@msackman Most of these are due to modifying an existing proto structure [here](https://github.com/livekit/livekit-server/blob/master/pkg/rtc/mediatrack.go#L102).

Agreed we should try to resolve these data race warnings. We could either introduce a Mutex for this operation, or clone it before modifying it.

If you are interested in taking a look, I'd welcome a PR!

**Comment by boks1971** [comment]
@msackman If you get a chance to try the latest in `master`, that would be great. There are a few races still in there, but those are purposely not addressed after analysing the code.

I am working on finding more reports of race and address them, but a majority of what you were seeing should be addressed in `master` now.

**Comment by msackman** [comment]
That's amazing - thank you. I kept meaning to come back to this bug and put some time in to try and address these issues but kept being too busy. Sorry. I should be able to take a look again in a few days I hope.

**Comment by boks1971** [comment]
Thank you @msackman .

**Comment by msackman** [comment]
Ok, I've had a quick play. I think it's better, but not fully done yet. I'm still seeing these with the latest from master.

```
WARNING: DATA RACE
Read at 0x00c001c8a11c by goroutine 217:
github.com/livekit/livekit-server/pkg/sfu/buffer.(*Buffer).buildReceptionReport()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/sfu/buffer/buffer.go:547 +0xbc
github.com/livekit/livekit-server/pkg/sfu/buffer.(*Buffer).getRTCP()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/sfu/buffer/buffer.go:568 +0x6d
github.com/livekit/livekit-server/pkg/sfu/buffer.(*Buffer).doReports()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/sfu/buffer/buffer.go:521 +0x8c
github.com/livekit/livekit-server/pkg/sfu/buffer.(*Buffer).calc()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/sfu/buffer/buffer.go:392 +0x32f
github.com/livekit/livekit-server/pkg/sfu/buffer.(*Buffer).Write()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/sfu/buffer/buffer.go:234 +0x1c9
github.com/pion/srtp/v2.(*ReadStreamSRTP).write()
/home/matthew/go/pkg/mod/github.com/pion/srtp/v2@v2.0.9/stream_srtp.go:64 +0x6a
github.com/pion/srtp/v2.(*SessionSRTP).decrypt()
/home/matthew/go/pkg/mod/github.com/pion/srtp/v2@v2.0.9/session_srtp.go:187 +0x20d
github.com/pion/srtp/v2.(*session).start.func1()
/home/matthew/go/pkg/mod/github.com/pion/srtp/v2@v2.0.9/session.go:142 +0x1de

Previous write at 0x00c001c8a11c by goroutine 204:
github.com/livekit/livekit-server/pkg/sfu/buffer.(*Buffer).SetLastFractionLostReport()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/sfu/buffer/buffer.go:562 +0xca
github.com/livekit/livekit-server/pkg/rtc.NewMediaTrack.func1()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/rtc/mediatrack.go:74 +0xa2
github.com/livekit/livekit-server/pkg/rtc.(*MediaTrackReceiver).maybeUpdateLoss()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/rtc/mediatrackreceiver.go:358 +0x1dd
github.com/livekit/livekit-server/pkg/rtc.(*MediaTrackReceiver).handleMaxLossFeedback()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/rtc/mediatrackreceiver.go:327 +0x8e
github.com/livekit/livekit-server/pkg/rtc.(*MediaTrackReceiver).handleMaxLossFeedback-fm()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/rtc/mediatrackreceiver.go:318 +0x4d
github.com/livekit/livekit-server/pkg/sfu.(*DownTrack).handleRTCP()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/sfu/downtrack.go:1075 +0xb19
github.com/livekit/livekit-server/pkg/sfu.(*DownTrack).Bind.func1()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/sfu/downtrack.go:261 +0x4e
github.com/livekit/livekit-server/pkg/sfu/buffer.(*RTCPReader).Write()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/sfu/buffer/rtcpreader.go:26 +0x7d
github.com/pion/srtp/v2.(*ReadStreamSRTCP).write()
/home/matthew/go/pkg/mod/github.com/pion/srtp/v2@v2.0.9/stream_srtcp.go:30 +0x6a
github.com/pion/srtp/v2.(*SessionSRTCP).decrypt()
/home/matthew/go/pkg/mod/github.com/pion/srtp/v2@v2.0.9/session_srtcp.go:176 +0x227
github.com/pion/srtp/v2.(*session).start.func1()
/home/matthew/go/pkg/mod/github.com/pion/srtp/v2@v2.0.9/session.go:142 +0x1de
```

and

```
Write at 0x00c001a50940 by goroutine 61:
github.com/livekit/livekit-server/pkg/rtc.(*Room).SetMetadata()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/rtc/room.go:541 +0x65
github.com/livekit/livekit-server/pkg/service.(*RoomManager).handleRTCMessage()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/service/roommanager.go:520 +0x7b7
github.com/livekit/livekit-server/pkg/service.(*RoomManager).handleRTCMessage-fm()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/service/roommanager.go:436 +0x97
github.com/livekit/livekit-server/pkg/routing.(*LocalRouter).rtcMessageWorker()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/routing/localrouter.go:223 +0x2ca
github.com/livekit/livekit-server/pkg/routing.(*LocalRouter).Start·dwrap·4()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/routing/localrouter.go:169 +0x39

Previous read at 0x00c001a50940 by goroutine 125:
google.golang.org/protobuf/internal/impl.appendStringNoZeroValidateUTF8()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/codec_gen.go:5021 +0x66
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/encode.go:139 +0x482
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshal()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/encode.go:107 +0xd0
google.golang.org/protobuf/internal/impl.(*MessageInfo).marshal-fm()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/encode.go:100 +0xd4
google.golang.org/protobuf/proto.MarshalOptions.marshal()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/proto/encode.go:163 +0x3b9
google.golang.org/protobuf/proto.Marshal()
/home/matthew/go/pkg/mod/google.golang.org/protobuf@v1.28.0/proto/encode.go:79 +0x59
github.com/livekit/protocol/livekit.(*roomServiceServer).serveUpdateRoomMetadataProtobuf()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.13.3-0.20220510071353-084233d23a03/livekit/livekit_room.twirp.go:3291 +0x3f8
github.com/livekit/protocol/livekit.(*roomServiceServer).serveUpdateRoomMetadata()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.13.3-0.20220510071353-084233d23a03/livekit/livekit_room.twirp.go:3139 +0x2fb
github.com/livekit/protocol/livekit.(*roomServiceServer).ServeHTTP()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.13.3-0.20220510071353-084233d23a03/livekit/livekit_room.twirp.go:1320 +0xdb0
net/http.(*ServeMux).ServeHTTP()
/nix/store/kdry395jlhj9pz97l0d71fmjqn2karbd-go-1.17.10/share/go/src/net/http/server.go:2425 +0xc5
github.com/urfave/negroni.Wrap.func1()
/home/matthew/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46 +0x69
```

**Comment by msackman** [comment]
Oh, just saw another when closing down a room:

```
WARNING: DATA RACE
Write at 0x00c00010e998 by goroutine 358:
github.com/livekit/livekit-server/pkg/routing.(*LocalRouter).WriteNodeRTC()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/routing/localrouter.go:144 +0x104
github.com/livekit/livekit-server/pkg/routing.(*LocalRouter).WriteRoomRTC()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/routing/localrouter.go:138 +0x124
github.com/livekit/livekit-server/pkg/service.(*RoomService).DeleteRoom()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/service/roomservice.go:80 +0x238
github.com/livekit/protocol/livekit.RoomService.DeleteRoom-fm()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.13.3-0.20220510071353-084233d23a03/livekit/livekit_room.twirp.go:41 +0x75
github.com/livekit/protocol/livekit.(*roomServiceServer).serveDeleteRoomProtobuf.func2()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.13.3-0.20220510071353-084233d23a03/livekit/livekit_room.twirp.go:1837 +0x18b
github.com/livekit/protocol/livekit.(*roomServiceServer).serveDeleteRoomProtobuf()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.13.3-0.20220510071353-084233d23a03/livekit/livekit_room.twirp.go:1838 +0x2fd
github.com/livekit/protocol/livekit.(*roomServiceServer).serveDeleteRoom()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.13.3-0.20220510071353-084233d23a03/livekit/livekit_room.twirp.go:1699 +0x2fb
github.com/livekit/protocol/livekit.(*roomServiceServer).ServeHTTP()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.13.3-0.20220510071353-084233d23a03/livekit/livekit_room.twirp.go:1296 +0x90e
net/http.(*ServeMux).ServeHTTP()
/nix/store/kdry395jlhj9pz97l0d71fmjqn2karbd-go-1.17.10/share/go/src/net/http/server.go:2425 +0xc5
github.com/urfave/negroni.Wrap.func1()
/home/matthew/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46 +0x69WARNING: DATA RACE
Write at 0x00c00010e998 by goroutine 358:
github.com/livekit/livekit-server/pkg/routing.(*LocalRouter).WriteNodeRTC()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/routing/localrouter.go:144 +0x104
github.com/livekit/livekit-server/pkg/routing.(*LocalRouter).WriteRoomRTC()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/routing/localrouter.go:138 +0x124
github.com/livekit/livekit-server/pkg/service.(*RoomService).DeleteRoom()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/service/roomservice.go:80 +0x238
github.com/livekit/protocol/livekit.RoomService.DeleteRoom-fm()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.13.3-0.20220510071353-084233d23a03/livekit/livekit_room.twirp.go:41 +0x75
github.com/livekit/protocol/livekit.(*roomServiceServer).serveDeleteRoomProtobuf.func2()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.13.3-0.20220510071353-084233d23a03/livekit/livekit_room.twirp.go:1837 +0x18b
github.com/livekit/protocol/livekit.(*roomServiceServer).serveDeleteRoomProtobuf()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.13.3-0.20220510071353-084233d23a03/livekit/livekit_room.twirp.go:1838 +0x2fd
github.com/livekit/protocol/livekit.(*roomServiceServer).serveDeleteRoom()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.13.3-0.20220510071353-084233d23a03/livekit/livekit_room.twirp.go:1699 +0x2fb
github.com/livekit/protocol/livekit.(*roomServiceServer).ServeHTTP()
/home/matthew/go/pkg/mod/github.com/livekit/protocol@v0.13.3-0.20220510071353-084233d23a03/livekit/livekit_room.twirp.go:1296 +0x90e
net/http.(*ServeMux).ServeHTTP()
/nix/store/kdry395jlhj9pz97l0d71fmjqn2karbd-go-1.17.10/share/go/src/net/http/server.go:2425 +0xc5
github.com/urfave/negroni.Wrap.func1()
/home/matthew/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46 +0x69
github.com/urfave/negroni.HandlerFunc.ServeHTTP()
/home/matthew/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29 +0x57
github.com/urfave/negroni.middleware.ServeHTTP()
/home/matthew/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x130
github.com/urfave/negroni.middleware.ServeHTTP-fm()
/home/matthew/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:37 +0x84
net/http.HandlerFunc.ServeHTTP()
/nix/store/kdry395jlhj9pz97l0d71fmjqn2karbd-go-1.17.10/share/go/src/net/http/server.go:2047 +0xccd
github.com/livekit/livekit-server/pkg/service.(*APIKeyAuthMiddleware).ServeHTTP()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/service/auth.go:82 +0x7d0

Previous read at 0x00c00010e998 by goroutine 377:
github.com/livekit/livekit-server/pkg/routing.(*LocalRouter).rtcMessageWorker()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/routing/localrouter.go:209 +0xc5
github.com/livekit/livekit-server/pkg/routing.(*LocalRouter).rtcMessageWorker.func1·dwrap·5()
/home/matthew/go/pkg/mod/github.com/livekit/livekit-server@v1.0.2-0.20220524075519-9d0e4375f260/pkg/routing/localrouter.go:206 +0x39
```

**Comment by boks1971** [comment]
@msackman Will appreciate another run with the latest `master` when you get a chance. I think I have addressed all the ones here (and there were also a few reported by running `go test -race`) except the last one you reported. We will look at that also soon. In the mean time, will appreciate if you are able to run and see anything new and if the other reported ones are gone.

**Comment by msackman** [comment]
Ok, I've just had another go. Curiously, livekit appears slightly unreliable for me in room creation just at the moment - I wonder if one of these data races is starting to cause problems. Nevertheless, with a little repetition, I can make it work.

This is with:

```
+       github.com/livekit/livekit-server v1.0.2-0.20220602181523-2927521b8bfe
+       github.com/livekit/protocol v0.13.3-0.20220530102138-51a8116f88b2
+       github.com/livekit/server-sdk-go v0.10.1-0.20220603080600-bf77157fb5af
```

```
Read at 0x00c001ac6160 by goroutine 174:
github.com/livekit/server-sdk-go.(*baseParticipant).SID()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1-0.20220603080600-bf77157fb5af/participant.go:63 +0x104
github.com/livekit/server-sdk-go.(*Room).handleSpeakersChange()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1-0.20220603080600-bf77157fb5af/room.go:302 +0xad
github.com/livekit/server-sdk-go.(*Room).handleSpeakersChange-fm()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1-0.20220603080600-bf77157fb5af/room.go:295 +0x57
...
Previous write at 0x00c001ac6160 by goroutine 26:
github.com/livekit/server-sdk-go.(*LocalParticipant).updateInfo()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1-0.20220603080600-bf77157fb5af/localparticipant.go:283 +0xb5
github.com/livekit/server-sdk-go.(*Room).JoinWithToken()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1-0.20220603080600-bf77157fb5af/room.go:139 +0x32c
github.com/livekit/server-sdk-go.(*Room).Join()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1-0.20220603080600-bf77157fb5af/room.go:118 +0x46e
```

However, that's the *only* one I'm now seeing, which is awesome.

(The following might all be red-herrings and unrelated to the above data race, not sure)

In general, in the room callbacks (via `server-sdk-go.NewRoomCallback`) it's not clear what should be locked by the callback to make data access safe. I'm using these callbacks extensively, but the API is a bit scary in terms of the lack of locks.

My code looks like this:

```go
func (self *Foo) CreateRoom(roomName string, roomMetaData string, callbacks *lksdk.RoomCallback) (*lksdk.Room, error) {
	roomClient := self.KeyMgr.NewRoomServiceClient(self.livekitURL)
	_, err := roomClient.CreateRoom(context.Background(), &livekit.CreateRoomRequest{
		Name:            roomName,
		EmptyTimeout:    uint32((1 * time.Minute).Seconds()),
		MaxParticipants: MaxMembersConst,
		Metadata:        roomMetaData,
	})
	if err != nil {
		return nil, err
	}
	connectInfo := self.KeyMgr.ConnectionInfo()
	connectInfo.RoomName = roomName
	connectInfo.ParticipantIdentity = `foobar`

	room := lksdk.CreateRoom()
	if callbacks != nil {
		room.Callback = callbacks
	}

	if err := room.Join(self.livekitURL, connectInfo, lksdk.WithAutoSubscribe(true)); err != nil {
		return nil, err
	}
	return room, nil
}
```

The assignment to `room.Callback = callbacks` is very scary - `CreateRoom()` already creates some callbacks and passes them into other datastructures. It's really not very clear what the intention is in terms of doing this safely. I've tried `*room.Callback = *callbacks` but that doesn't really seem any better. It would be much nicer, to me, if `CreateRoom()` took optional callbacks as a parameter, and so you could be certain that from the point of creation onwards, your callbacks had been correctly propagated everywhere - no data races could happen.

**Comment by davidzhao** [comment]
@msackman we have yet to go through a pass with the Go SDK on data race. However, we did fix an issue that would result in connection failures when used against the latest unreleased version of the server. The summary is that we've made a bunch of improvements in server performance that exposes a timing issue in Go SDK. Try the latest commit in server-sdk-go.

Callbacks shouldn't really have a race condition as they should be set prior to spinning up any Goroutines.

**Comment by msackman** [comment]
ok, I've just done another test with:

```
+       github.com/livekit/livekit-server v1.0.2-0.20220610043134-15da445fd7ab
+       github.com/livekit/protocol v0.13.3-0.20220608063907-5e0777215366
+       github.com/livekit/server-sdk-go v0.10.1
```

I'm not seeing any more races in livekit-server. The only races I'm seeing are in the server sdk (and in my own code too!).

```
Write at 0x00c0023b8640 by goroutine 122:
github.com/livekit/server-sdk-go.(*baseParticipant).updateInfo()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/participant.go:149 +0xd1
github.com/livekit/server-sdk-go.(*RemoteParticipant).updateInfo()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/remoteparticipant.go:29 +0x84
github.com/livekit/server-sdk-go.(*Room).handleParticipantUpdate()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/room.go:247 +0xfb
github.com/livekit/server-sdk-go.(*Room).handleParticipantUpdate-fm()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/room.go:231 +0x57

Previous read at 0x00c0023b8640 by goroutine 265:
github.com/livekit/server-sdk-go.(*baseParticipant).Identity()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/participant.go:67 +0x1c4
(*foo).onParticipantConnected()
***:267 +0x1b9
(*foo).onParticipantConnected-fm()
***:255 +0x44
github.com/livekit/server-sdk-go.(*Room).handleParticipantUpdate·dwrap·17()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/room.go:244 +0x47
```

```
Write at 0x00c0023b8650 by goroutine 122:
github.com/livekit/server-sdk-go.(*baseParticipant).updateInfo()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/participant.go:151 +0x1ab
github.com/livekit/server-sdk-go.(*RemoteParticipant).updateInfo()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/remoteparticipant.go:29 +0x84
github.com/livekit/server-sdk-go.(*Room).handleParticipantUpdate()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/room.go:247 +0xfb
github.com/livekit/server-sdk-go.(*Room).handleParticipantUpdate-fm()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/room.go:231 +0x57
github.com/livekit/server-sdk-go.(*SignalClient).handleResponse()

Previous read at 0x00c0023b8650 by goroutine 265:
github.com/livekit/server-sdk-go.(*baseParticipant).Name()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/participant.go:71 +0x21d
(*foo).onParticipantConnected()
***.go:271 +0x141
(*foo).onParticipantConnected-fm()
***.go:255 +0x44
github.com/livekit/server-sdk-go.(*Room).handleParticipantUpdate·dwrap·17()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/room.go:244 +0x47
```

```
Read at 0x00c000e40210 by goroutine 122:
github.com/livekit/server-sdk-go.(*baseParticipant).SID()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/participant.go:63 +0x104
github.com/livekit/server-sdk-go.(*Room).handleSpeakersChange()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/room.go:302 +0xad
github.com/livekit/server-sdk-go.(*Room).handleSpeakersChange-fm()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/room.go:295 +0x57
github.com/livekit/server-sdk-go.(*SignalClient).handleResponse()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/signalclient.go:220 +0x9d1

Previous write at 0x00c000e40210 by goroutine 138:
github.com/livekit/server-sdk-go.(*LocalParticipant).updateInfo()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/localparticipant.go:283 +0xb5
github.com/livekit/server-sdk-go.(*Room).JoinWithToken()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/room.go:139 +0x32c
github.com/livekit/server-sdk-go.(*Room).Join()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/room.go:118 +0x46e
```

```
Read at 0x00c000e40220 by goroutine 149:
github.com/livekit/server-sdk-go.(*baseParticipant).Identity()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/participant.go:67 +0x34
github.com/livekit/server-sdk-go.(*LocalParticipant).Identity()
<autogenerated>:1 +0x37
(*foo).onActiveSpeakersChanged()
***.go:310 +0x3f9

Previous write at 0x00c000e40220 by goroutine 138:
github.com/livekit/server-sdk-go.(*LocalParticipant).updateInfo()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/localparticipant.go:284 +0x125
github.com/livekit/server-sdk-go.(*Room).JoinWithToken()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/room.go:139 +0x32c
github.com/livekit/server-sdk-go.(*Room).Join()
/home/matthew/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.1/room.go:118 +0x46e
```

Thank you so much for all your work, time, and effort on this project - without which I just wouldn't be able to do what I'm currently doing.

**Comment by davidzhao** [comment]
Thanks for confirming @msackman ! I'm going to close this issue and open one for Go SDK.
